classdef aten__add124 < nnet.layer.Layer & nnet.layer.Formattable & ...
        nnet.layer.AutogeneratedFromPyTorch
    %aten__add124 Auto-generated custom layer
    % Auto-generated by MATLAB on 04-Sep-2026 18:43:57

    properties (Learnable)
        % Networks (type dlnetwork)

    end

    properties
        % Non-Trainable Parameters
        add_28



    end

    properties (Learnable)
        % Trainable Parameters

    end

    methods
        function obj = aten__add124(Name, Type, InputNames, OutputNames)
            obj.Name = Name;
            obj.Type = Type;
            obj.NumInputs = 4;
            obj.NumOutputs = 2;
            obj.InputNames = InputNames;
            obj.OutputNames = OutputNames;
        end

        function [add_42, add_42_rank] = predict(obj,add_36, add_input_1, add_36_rank, add_input_1_rank)

            %Use the input format inferred by the importer to permute the input into reverse-PyTorch dimension order
            [add_36, add_36_format] = segformer_eager.ops.permuteToReversePyTorch(add_36, '', numel(add_36_rank));

            %Use the input format inferred by the importer to permute the input into reverse-PyTorch dimension order
            [add_input_1, add_input_1_format] = segformer_eager.ops.permuteToReversePyTorch(add_input_1, '', numel(add_input_1_rank));
            [add_36] = struct('value', add_36, 'rank', int64(max([2, ndims(add_36), numel(add_36_rank)])));
            [add_input_1] = struct('value', add_input_1, 'rank', int64(max([2, ndims(add_input_1), numel(add_input_1_rank)])));

            [add_42] = tracedPyTorchFunction(obj,add_36, add_input_1,false,"predict");

            [add_42_rank] = ones([1,add_42.rank], 'single');
            add_42_rank = dlarray(add_42_rank,'UU');
            %Permute U-labelled output to forward PyTorch dimension ordering
            if(isa(add_42.value,'dlarray') && any(dims(add_42.value) == 'U'))
                add_42 = permute(add_42.value, fliplr(1:max(2,add_42.rank)));
            else
                add_42 = dlarray(single(add_42.value), 'UU');
            end

        end



        function [add_42, add_42_rank] = forward(obj,add_36, add_input_1, add_36_rank, add_input_1_rank)

            %Use the input format inferred by the importer to permute the input into reverse-PyTorch dimension order
            [add_36, add_36_format] = segformer_eager.ops.permuteToReversePyTorch(add_36, '', numel(add_36_rank));

            %Use the input format inferred by the importer to permute the input into reverse-PyTorch dimension order
            [add_input_1, add_input_1_format] = segformer_eager.ops.permuteToReversePyTorch(add_input_1, '', numel(add_input_1_rank));
            [add_36] = struct('value', add_36, 'rank', int64(max([2, ndims(add_36), numel(add_36_rank)])));
            [add_input_1] = struct('value', add_input_1, 'rank', int64(max([2, ndims(add_input_1), numel(add_input_1_rank)])));

            [add_42] = tracedPyTorchFunction(obj,add_36, add_input_1,true,"forward");

            [add_42_rank] = ones([1,add_42.rank], 'single');
            add_42_rank = dlarray(add_42_rank,'UU');
            %Permute U-labelled output to forward PyTorch dimension ordering
            if(isa(add_42.value,'dlarray') && any(dims(add_42.value) == 'U'))
                add_42 = permute(add_42.value, fliplr(1:max(2,add_42.rank)));
            else
                add_42 = dlarray(single(add_42.value), 'UU');
            end

        end



        function [add_42] = tracedPyTorchFunction(obj,add_36, add_input_1,isForward,predict)

            [add_28] = segformer_eager.ops.makeStructForConstant(int64(obj.add_28), int64(0), "Typed");
            [add_42] = segformer_eager.ops.pyElementwiseBinary(add_36, add_input_1, 'plus', add_28);
        end

    end
end

