classdef aten__linear37 < nnet.layer.Layer & nnet.layer.Formattable & ...
        nnet.layer.AutogeneratedFromPyTorch & nnet.layer.Acceleratable
    %aten__linear37 Auto-generated custom layer
    % Auto-generated by MATLAB on 04-Sep-2026 18:43:39

    properties (Learnable)
        % Networks (type dlnetwork)

    end

    properties
        % Non-Trainable Parameters




    end

    properties (Learnable)
        % Trainable Parameters
        Param_weight
        Param_bias
    end

    methods
        function obj = aten__linear37(Name, Type, InputNames, OutputNames)
            obj.Name = Name;
            obj.Type = Type;
            obj.NumInputs = 1;
            obj.NumOutputs = 1;
            obj.InputNames = InputNames;
            obj.OutputNames = OutputNames;
        end

        function [linear_9] = predict(obj,linear_argument1_1)

            %Use the input format inferred by the importer to permute the input into reverse-PyTorch dimension order
            [linear_argument1_1, linear_argument1_1_format] = segformer_eager.ops.permuteToReversePyTorch(linear_argument1_1, '', 3);
            [linear_argument1_1] = struct('value', linear_argument1_1, 'rank', int64(3));

            [linear_9] = tracedPyTorchFunction(obj,linear_argument1_1,false,"predict");


            %Permute U-labelled output to forward PyTorch dimension ordering
            if(isa(linear_9.value,'dlarray') && any(dims(linear_9.value) == 'U'))
                linear_9 = permute(linear_9.value, fliplr(1:max(2,linear_9.rank)));
            else
                linear_9 = dlarray(single(linear_9.value), 'UU');
            end

        end



        function [linear_9] = forward(obj,linear_argument1_1)

            %Use the input format inferred by the importer to permute the input into reverse-PyTorch dimension order
            [linear_argument1_1, linear_argument1_1_format] = segformer_eager.ops.permuteToReversePyTorch(linear_argument1_1, '', 3);
            [linear_argument1_1] = struct('value', linear_argument1_1, 'rank', int64(3));

            [linear_9] = tracedPyTorchFunction(obj,linear_argument1_1,true,"forward");


            %Permute U-labelled output to forward PyTorch dimension ordering
            if(isa(linear_9.value,'dlarray') && any(dims(linear_9.value) == 'U'))
                linear_9 = permute(linear_9.value, fliplr(1:max(2,linear_9.rank)));
            else
                linear_9 = dlarray(single(linear_9.value), 'UU');
            end

        end



        function [linear_9] = tracedPyTorchFunction(obj,linear_argument1_1,isForward,predict)

            linear_weight_1 = obj.Param_weight;

            [linear_weight_1] = struct('value', dlarray(linear_weight_1,'UU'), 'rank', 2);

            linear_bias_1 = obj.Param_bias;

            [linear_bias_1] = struct('value', dlarray(linear_bias_1,'UU'), 'rank', 1);

            [linear_9] = segformer_eager.ops.pyLinear(linear_argument1_1, linear_weight_1, linear_bias_1);
        end

    end
end

