classdef aten__layer_norm23 < nnet.layer.Layer & nnet.layer.Formattable & ...
        nnet.layer.AutogeneratedFromPyTorch & nnet.layer.Acceleratable
    %aten__layer_norm23 Auto-generated custom layer
    % Auto-generated by MATLAB on 04-Sep-2026 18:43:34

    properties (Learnable)
        % Networks (type dlnetwork)

    end

    properties
        % Non-Trainable Parameters
        layernorm_24
        layernorm_11
        layernorm_12



    end

    properties (Learnable)
        % Trainable Parameters
        Param_weight
        Param_bias
    end

    methods
        function obj = aten__layer_norm23(Name, Type, InputNames, OutputNames)
            obj.Name = Name;
            obj.Type = Type;
            obj.NumInputs = 2;
            obj.NumOutputs = 2;
            obj.InputNames = InputNames;
            obj.OutputNames = OutputNames;
        end

        function [layernorm_input0_1, layernorm_input0_1_rank] = predict(obj,layernorm_input_1, layernorm_input_1_rank)

            %Use the input format inferred by the importer to permute the input into reverse-PyTorch dimension order
            [layernorm_input_1, layernorm_input_1_format] = segformer_eager.ops.permuteToReversePyTorch(layernorm_input_1, '', numel(layernorm_input_1_rank));
            [layernorm_input_1] = struct('value', layernorm_input_1, 'rank', int64(max([2, ndims(layernorm_input_1), numel(layernorm_input_1_rank)])));

            [layernorm_input0_1] = tracedPyTorchFunction(obj,layernorm_input_1,false,"predict");

            [layernorm_input0_1_rank] = segformer_eager.ops.onesRankLike(layernorm_input0_1.rank, layernorm_input0_1.value);
            layernorm_input0_1_rank = dlarray(layernorm_input0_1_rank,'UU');
            %Permute U-labelled output to forward PyTorch dimension ordering
            if(isa(layernorm_input0_1.value,'dlarray') && any(dims(layernorm_input0_1.value) == 'U'))
                layernorm_input0_1 = permute(layernorm_input0_1.value, fliplr(1:max(2,layernorm_input0_1.rank)));
            else
                layernorm_input0_1 = dlarray(single(layernorm_input0_1.value), 'UU');
            end

        end



        function [layernorm_input0_1, layernorm_input0_1_rank] = forward(obj,layernorm_input_1, layernorm_input_1_rank)

            %Use the input format inferred by the importer to permute the input into reverse-PyTorch dimension order
            [layernorm_input_1, layernorm_input_1_format] = segformer_eager.ops.permuteToReversePyTorch(layernorm_input_1, '', numel(layernorm_input_1_rank));
            [layernorm_input_1] = struct('value', layernorm_input_1, 'rank', int64(max([2, ndims(layernorm_input_1), numel(layernorm_input_1_rank)])));

            [layernorm_input0_1] = tracedPyTorchFunction(obj,layernorm_input_1,true,"forward");

            [layernorm_input0_1_rank] = segformer_eager.ops.onesRankLike(layernorm_input0_1.rank, layernorm_input0_1.value);
            layernorm_input0_1_rank = dlarray(layernorm_input0_1_rank,'UU');
            %Permute U-labelled output to forward PyTorch dimension ordering
            if(isa(layernorm_input0_1.value,'dlarray') && any(dims(layernorm_input0_1.value) == 'U'))
                layernorm_input0_1 = permute(layernorm_input0_1.value, fliplr(1:max(2,layernorm_input0_1.rank)));
            else
                layernorm_input0_1 = dlarray(single(layernorm_input0_1.value), 'UU');
            end

        end



        function [layernorm_input0_1] = tracedPyTorchFunction(obj,layernorm_input_1,isForward,predict)

            [layernorm_24] = segformer_eager.ops.makeStructForConstant(int64(obj.layernorm_24), int64(1), "Typed");
            layernorm_weight_1 = obj.Param_weight;

            [layernorm_weight_1] = struct('value', dlarray(layernorm_weight_1,'UU'), 'rank', 1);

            layernorm_bias_1 = obj.Param_bias;

            [layernorm_bias_1] = struct('value', dlarray(layernorm_bias_1,'UU'), 'rank', 1);

            [layernorm_11] = segformer_eager.ops.makeStructForConstant(single(obj.layernorm_11), int64(0), "Typed");
            [layernorm_12] = segformer_eager.ops.makeStructForConstant(int64(obj.layernorm_12), int64(0), "Typed");
            [layernorm_input0_1] = segformer_eager.ops.pyLayerNorm(layernorm_input_1, layernorm_24, layernorm_weight_1, layernorm_bias_1, layernorm_11);
        end

    end
end

