classdef aten__gelu25 < nnet.layer.Layer & nnet.layer.Formattable & ...
        nnet.layer.AutogeneratedFromPyTorch
    %aten__gelu25 Auto-generated custom layer
    % Auto-generated by MATLAB on 04-Sep-2026 18:43:35

    properties (Learnable)
        % Networks (type dlnetwork)

    end

    properties
        % Non-Trainable Parameters
        gelu_3



    end

    properties (Learnable)
        % Trainable Parameters

    end

    methods
        function obj = aten__gelu25(Name, Type, InputNames, OutputNames)
            obj.Name = Name;
            obj.Type = Type;
            obj.NumInputs = 2;
            obj.NumOutputs = 2;
            obj.InputNames = InputNames;
            obj.OutputNames = OutputNames;
        end

        function [gelu_4, gelu_4_rank] = predict(obj,gelu_argument1_1, gelu_argument1_1_rank)

            %Use the input format inferred by the importer to permute the input into reverse-PyTorch dimension order
            [gelu_argument1_1, gelu_argument1_1_format] = segformer_eager.ops.permuteToReversePyTorch(gelu_argument1_1, '', numel(gelu_argument1_1_rank));
            [gelu_argument1_1] = struct('value', gelu_argument1_1, 'rank', int64(max([2, ndims(gelu_argument1_1), numel(gelu_argument1_1_rank)])));

            [gelu_4] = tracedPyTorchFunction(obj,gelu_argument1_1,false,"predict");

            [gelu_4_rank] = segformer_eager.ops.onesRankLike(gelu_4.rank, gelu_4.value);
            gelu_4_rank = dlarray(gelu_4_rank,'UU');
            %Permute U-labelled output to forward PyTorch dimension ordering
            if(isa(gelu_4.value,'dlarray') && any(dims(gelu_4.value) == 'U'))
                gelu_4 = permute(gelu_4.value, fliplr(1:max(2,gelu_4.rank)));
            else
                gelu_4 = dlarray(single(gelu_4.value), 'UU');
            end

        end



        function [gelu_4, gelu_4_rank] = forward(obj,gelu_argument1_1, gelu_argument1_1_rank)

            %Use the input format inferred by the importer to permute the input into reverse-PyTorch dimension order
            [gelu_argument1_1, gelu_argument1_1_format] = segformer_eager.ops.permuteToReversePyTorch(gelu_argument1_1, '', numel(gelu_argument1_1_rank));
            [gelu_argument1_1] = struct('value', gelu_argument1_1, 'rank', int64(max([2, ndims(gelu_argument1_1), numel(gelu_argument1_1_rank)])));

            [gelu_4] = tracedPyTorchFunction(obj,gelu_argument1_1,true,"forward");

            [gelu_4_rank] = segformer_eager.ops.onesRankLike(gelu_4.rank, gelu_4.value);
            gelu_4_rank = dlarray(gelu_4_rank,'UU');
            %Permute U-labelled output to forward PyTorch dimension ordering
            if(isa(gelu_4.value,'dlarray') && any(dims(gelu_4.value) == 'U'))
                gelu_4 = permute(gelu_4.value, fliplr(1:max(2,gelu_4.rank)));
            else
                gelu_4 = dlarray(single(gelu_4.value), 'UU');
            end

        end



        function [gelu_4] = tracedPyTorchFunction(obj,gelu_argument1_1,isForward,predict)

            [gelu_3] = segformer_eager.ops.makeStructForConstant(string(obj.gelu_3), int64(0), "Typed");
            [gelu_4] = segformer_eager.ops.pyGelu(gelu_argument1_1, gelu_3);
        end

    end
end

