classdef aten__add30 < nnet.layer.Layer & nnet.layer.Formattable & ...
        nnet.layer.AutogeneratedFromPyTorch
    %aten__add30 Auto-generated custom layer
    % Auto-generated by MATLAB on 04-Sep-2026 18:43:35

    properties (Learnable)
        % Networks (type dlnetwork)

    end

    properties
        % Non-Trainable Parameters
        add_33



    end

    properties (Learnable)
        % Trainable Parameters

    end

    methods
        function obj = aten__add30(Name, Type, InputNames, OutputNames)
            obj.Name = Name;
            obj.Type = Type;
            obj.NumInputs = 4;
            obj.NumOutputs = 2;
            obj.InputNames = InputNames;
            obj.OutputNames = OutputNames;
        end

        function [add_47, add_47_rank] = predict(obj,add_41, add_input_1, add_41_rank, add_input_1_rank)

            %Use the input format inferred by the importer to permute the input into reverse-PyTorch dimension order
            [add_41, add_41_format] = segformer_eager.ops.permuteToReversePyTorch(add_41, '', numel(add_41_rank));

            %Use the input format inferred by the importer to permute the input into reverse-PyTorch dimension order
            [add_input_1, add_input_1_format] = segformer_eager.ops.permuteToReversePyTorch(add_input_1, '', numel(add_input_1_rank));
            [add_41] = struct('value', add_41, 'rank', int64(max([2, ndims(add_41), numel(add_41_rank)])));
            [add_input_1] = struct('value', add_input_1, 'rank', int64(max([2, ndims(add_input_1), numel(add_input_1_rank)])));

            [add_47] = tracedPyTorchFunction(obj,add_41, add_input_1,false,"predict");

            [add_47_rank] = ones([1,add_47.rank], 'single');
            add_47_rank = dlarray(add_47_rank,'UU');
            %Permute U-labelled output to forward PyTorch dimension ordering
            if(isa(add_47.value,'dlarray') && any(dims(add_47.value) == 'U'))
                add_47 = permute(add_47.value, fliplr(1:max(2,add_47.rank)));
            else
                add_47 = dlarray(single(add_47.value), 'UU');
            end

        end



        function [add_47, add_47_rank] = forward(obj,add_41, add_input_1, add_41_rank, add_input_1_rank)

            %Use the input format inferred by the importer to permute the input into reverse-PyTorch dimension order
            [add_41, add_41_format] = segformer_eager.ops.permuteToReversePyTorch(add_41, '', numel(add_41_rank));

            %Use the input format inferred by the importer to permute the input into reverse-PyTorch dimension order
            [add_input_1, add_input_1_format] = segformer_eager.ops.permuteToReversePyTorch(add_input_1, '', numel(add_input_1_rank));
            [add_41] = struct('value', add_41, 'rank', int64(max([2, ndims(add_41), numel(add_41_rank)])));
            [add_input_1] = struct('value', add_input_1, 'rank', int64(max([2, ndims(add_input_1), numel(add_input_1_rank)])));

            [add_47] = tracedPyTorchFunction(obj,add_41, add_input_1,true,"forward");

            [add_47_rank] = ones([1,add_47.rank], 'single');
            add_47_rank = dlarray(add_47_rank,'UU');
            %Permute U-labelled output to forward PyTorch dimension ordering
            if(isa(add_47.value,'dlarray') && any(dims(add_47.value) == 'U'))
                add_47 = permute(add_47.value, fliplr(1:max(2,add_47.rank)));
            else
                add_47 = dlarray(single(add_47.value), 'UU');
            end

        end



        function [add_47] = tracedPyTorchFunction(obj,add_41, add_input_1,isForward,predict)

            [add_33] = segformer_eager.ops.makeStructForConstant(int64(obj.add_33), int64(0), "Typed");
            [add_47] = segformer_eager.ops.pyElementwiseBinary(add_41, add_input_1, 'plus', add_33);
        end

    end
end

