classdef aten__add29 < nnet.layer.Layer & nnet.layer.Formattable & ...
        nnet.layer.AutogeneratedFromPyTorch
    %aten__add29 Auto-generated custom layer
    % Auto-generated by MATLAB on 04-Sep-2026 18:43:34

    properties (Learnable)
        % Networks (type dlnetwork)

    end

    properties
        % Non-Trainable Parameters
        add_33



    end

    properties (Learnable)
        % Trainable Parameters

    end

    methods
        function obj = aten__add29(Name, Type, InputNames, OutputNames)
            obj.Name = Name;
            obj.Type = Type;
            obj.NumInputs = 4;
            obj.NumOutputs = 3;
            obj.InputNames = InputNames;
            obj.OutputNames = OutputNames;
        end

        function [add_input_1, add_input_1_rank] = predict(obj,add_28, add_argument1_1, add_28_rank, add_argument1_1_rank)

            %Use the input format inferred by the importer to permute the input into reverse-PyTorch dimension order
            [add_28, add_28_format] = segformer_eager.ops.permuteToReversePyTorch(add_28, '', numel(add_28_rank));

            %Use the input format inferred by the importer to permute the input into reverse-PyTorch dimension order
            [add_argument1_1, add_argument1_1_format] = segformer_eager.ops.permuteToReversePyTorch(add_argument1_1, '', numel(add_argument1_1_rank));
            [add_28] = struct('value', add_28, 'rank', int64(max([2, ndims(add_28), numel(add_28_rank)])));
            [add_argument1_1] = struct('value', add_argument1_1, 'rank', int64(max([2, ndims(add_argument1_1), numel(add_argument1_1_rank)])));

            [add_input_1] = tracedPyTorchFunction(obj,add_28, add_argument1_1,false,"predict");

            [add_input_1_rank] = ones([1,add_input_1.rank], 'single');
            add_input_1_rank = dlarray(add_input_1_rank,'UU');
            %Permute U-labelled output to forward PyTorch dimension ordering
            if(isa(add_input_1.value,'dlarray') && any(dims(add_input_1.value) == 'U'))
                add_input_1 = permute(add_input_1.value, fliplr(1:max(2,add_input_1.rank)));
            else
                add_input_1 = dlarray(single(add_input_1.value), 'UU');
            end

        end



        function [add_input_1, add_input_1_rank] = forward(obj,add_28, add_argument1_1, add_28_rank, add_argument1_1_rank)

            %Use the input format inferred by the importer to permute the input into reverse-PyTorch dimension order
            [add_28, add_28_format] = segformer_eager.ops.permuteToReversePyTorch(add_28, '', numel(add_28_rank));

            %Use the input format inferred by the importer to permute the input into reverse-PyTorch dimension order
            [add_argument1_1, add_argument1_1_format] = segformer_eager.ops.permuteToReversePyTorch(add_argument1_1, '', numel(add_argument1_1_rank));
            [add_28] = struct('value', add_28, 'rank', int64(max([2, ndims(add_28), numel(add_28_rank)])));
            [add_argument1_1] = struct('value', add_argument1_1, 'rank', int64(max([2, ndims(add_argument1_1), numel(add_argument1_1_rank)])));

            [add_input_1] = tracedPyTorchFunction(obj,add_28, add_argument1_1,true,"forward");

            [add_input_1_rank] = ones([1,add_input_1.rank], 'single');
            add_input_1_rank = dlarray(add_input_1_rank,'UU');
            %Permute U-labelled output to forward PyTorch dimension ordering
            if(isa(add_input_1.value,'dlarray') && any(dims(add_input_1.value) == 'U'))
                add_input_1 = permute(add_input_1.value, fliplr(1:max(2,add_input_1.rank)));
            else
                add_input_1 = dlarray(single(add_input_1.value), 'UU');
            end

        end



        function [add_input_1] = tracedPyTorchFunction(obj,add_28, add_argument1_1,isForward,predict)

            [add_33] = segformer_eager.ops.makeStructForConstant(int64(obj.add_33), int64(0), "Typed");
            [add_input_1] = segformer_eager.ops.pyElementwiseBinary(add_28, add_argument1_1, 'plus', add_33);
        end

    end
end

