classdef modelingsegformer_torchmangle162_SegformerStage < nnet.layer.Layer & nnet.layer.Formattable & ...
        nnet.layer.AutogeneratedFromPyTorch & nnet.layer.Acceleratable
    %modelingsegformer_torchmangle162_SegformerStage Auto-generated custom layer
    % Auto-generated by MATLAB on 04-Sep-2026 18:43:57

    properties (Learnable)
        % Networks (type dlnetwork)

        Param_patch_embeddings
        Param_blocks_0
        Param_blocks_1
        Param_layer_norm
    end

    properties
        % Non-Trainable Parameters
        Constant_38
        Constant_47
        Constant_68



    end

    properties (Learnable)
        % Trainable Parameters

    end

    methods
        function obj = modelingsegformer_torchmangle162_SegformerStage(Name, Type, InputNames, OutputNames)
            obj.Name = Name;
            obj.Type = Type;
            obj.NumInputs = 1;
            obj.NumOutputs = 2;
            obj.InputNames = InputNames;
            obj.OutputNames = OutputNames;
        end

        function [contiguous_encoderhiddenstate_1, contiguous_encoderhiddenstate_1_rank] = predict(obj,CallMethod_argument1_1)

            %Use the input format inferred by the importer to permute the input into reverse-PyTorch dimension order
            [CallMethod_argument1_1, CallMethod_argument1_1_format] = segformer_eager.ops.permuteToReversePyTorch(CallMethod_argument1_1, '*CSS', '');

            if ~contains(CallMethod_argument1_1_format,'U')
                [CallMethod_argument1_1] = struct('value', CallMethod_argument1_1, 'rank', numel(CallMethod_argument1_1_format));
            end

            [contiguous_encoderhiddenstate_1] = tracedPyTorchFunction(obj,CallMethod_argument1_1,false,"predict");

            [contiguous_encoderhiddenstate_1_rank] = segformer_eager.ops.onesRankLike(contiguous_encoderhiddenstate_1.rank, contiguous_encoderhiddenstate_1.value);
            contiguous_encoderhiddenstate_1_rank = dlarray(contiguous_encoderhiddenstate_1_rank,'UU');
            %Permute U-labelled output to forward PyTorch dimension ordering
            if(isa(contiguous_encoderhiddenstate_1.value,'dlarray') && any(dims(contiguous_encoderhiddenstate_1.value) == 'U'))
                contiguous_encoderhiddenstate_1 = permute(contiguous_encoderhiddenstate_1.value, fliplr(1:max(2,contiguous_encoderhiddenstate_1.rank)));
            else
                contiguous_encoderhiddenstate_1 = dlarray(single(contiguous_encoderhiddenstate_1.value), 'UU');
            end

        end



        function [contiguous_encoderhiddenstate_1, contiguous_encoderhiddenstate_1_rank] = forward(obj,CallMethod_argument1_1)

            %Use the input format inferred by the importer to permute the input into reverse-PyTorch dimension order
            [CallMethod_argument1_1, CallMethod_argument1_1_format] = segformer_eager.ops.permuteToReversePyTorch(CallMethod_argument1_1, '*CSS', '');

            if ~contains(CallMethod_argument1_1_format,'U')
                [CallMethod_argument1_1] = struct('value', CallMethod_argument1_1, 'rank', numel(CallMethod_argument1_1_format));
            end

            [contiguous_encoderhiddenstate_1] = tracedPyTorchFunction(obj,CallMethod_argument1_1,true,"forward");

            [contiguous_encoderhiddenstate_1_rank] = segformer_eager.ops.onesRankLike(contiguous_encoderhiddenstate_1.rank, contiguous_encoderhiddenstate_1.value);
            contiguous_encoderhiddenstate_1_rank = dlarray(contiguous_encoderhiddenstate_1_rank,'UU');
            %Permute U-labelled output to forward PyTorch dimension ordering
            if(isa(contiguous_encoderhiddenstate_1.value,'dlarray') && any(dims(contiguous_encoderhiddenstate_1.value) == 'U'))
                contiguous_encoderhiddenstate_1 = permute(contiguous_encoderhiddenstate_1.value, fliplr(1:max(2,contiguous_encoderhiddenstate_1.rank)));
            else
                contiguous_encoderhiddenstate_1 = dlarray(single(contiguous_encoderhiddenstate_1.value), 'UU');
            end

        end



        function [contiguous_encoderhiddenstate_1] = tracedPyTorchFunction(obj,CallMethod_argument1_1,isForward,predict)

            [Constant_38] = segformer_eager.ops.makeStructForConstant(int64(obj.Constant_38), int64(0), "Typed");
            [Constant_47] = segformer_eager.ops.makeStructForConstant(int64(obj.Constant_47), int64(0), "Typed");
            GetAttr_layernorm_1 = obj.Param_layer_norm;


            GetAttr_1 = obj.Param_blocks_1;


            GetAttr_0 = obj.Param_blocks_0;


            GetAttr_patchembeddings_1 = obj.Param_patch_embeddings;

            GetAttr_patchembeddings_1_InputFormat1 = '*CSS';


            [CallMethod_argument1_1_labelled] = segformer_eager.ops.labelWithPropagatedFormats(CallMethod_argument1_1, GetAttr_patchembeddings_1_InputFormat1);
            [CallMethod_18,CallMethod_19,CallMethod_20,CallMethod_21,CallMethod_22,CallMethod_23,CallMethod_24,CallMethod_18_rank,CallMethod_19_rank,CallMethod_20_rank,CallMethod_21_rank,CallMethod_22_rank,CallMethod_23_rank,CallMethod_24_rank] = GetAttr_patchembeddings_1.(predict)(CallMethod_argument1_1_labelled.value);
            [CallMethod_18, CallMethod_18_format] = segformer_eager.ops.permuteToReversePyTorch(CallMethod_18, '', int64(numel(CallMethod_18_rank)));[CallMethod_19, CallMethod_19_format] = segformer_eager.ops.permuteToReversePyTorch(CallMethod_19, '', int64(numel(CallMethod_19_rank)));[CallMethod_20, CallMethod_20_format] = segformer_eager.ops.permuteToReversePyTorch(CallMethod_20, '', int64(numel(CallMethod_20_rank)));[CallMethod_21, CallMethod_21_format] = segformer_eager.ops.permuteToReversePyTorch(CallMethod_21, '', int64(numel(CallMethod_21_rank)));[CallMethod_22, CallMethod_22_format] = segformer_eager.ops.permuteToReversePyTorch(CallMethod_22, '', int64(numel(CallMethod_22_rank)));[CallMethod_23, CallMethod_23_format] = segformer_eager.ops.permuteToReversePyTorch(CallMethod_23, '', int64(numel(CallMethod_23_rank)));[CallMethod_24, CallMethod_24_format] = segformer_eager.ops.permuteToReversePyTorch(CallMethod_24, '', int64(numel(CallMethod_24_rank)));
            if ~contains(CallMethod_18_format,'U')
                [CallMethod_18] = struct('value', CallMethod_18, 'rank', numel(CallMethod_18_format));
            else
                [CallMethod_18] = struct('value', CallMethod_18, 'rank', int64(max([2, ndims(CallMethod_18), numel(CallMethod_18_rank)])));
            end
            if ~contains(CallMethod_19_format,'U')
                [CallMethod_19] = struct('value', CallMethod_19, 'rank', numel(CallMethod_19_format));
            else
                [CallMethod_19] = struct('value', CallMethod_19, 'rank', int64(max([2, ndims(CallMethod_19), numel(CallMethod_19_rank)])));
            end
            if ~contains(CallMethod_20_format,'U')
                [CallMethod_20] = struct('value', CallMethod_20, 'rank', numel(CallMethod_20_format));
            else
                [CallMethod_20] = struct('value', CallMethod_20, 'rank', int64(max([2, ndims(CallMethod_20), numel(CallMethod_20_rank)])));
            end
            if ~contains(CallMethod_21_format,'U')
                [CallMethod_21] = struct('value', CallMethod_21, 'rank', numel(CallMethod_21_format));
            else
                [CallMethod_21] = struct('value', CallMethod_21, 'rank', int64(max([2, ndims(CallMethod_21), numel(CallMethod_21_rank)])));
            end
            if ~contains(CallMethod_22_format,'U')
                [CallMethod_22] = struct('value', CallMethod_22, 'rank', numel(CallMethod_22_format));
            else
                [CallMethod_22] = struct('value', CallMethod_22, 'rank', int64(max([2, ndims(CallMethod_22), numel(CallMethod_22_rank)])));
            end
            if ~contains(CallMethod_23_format,'U')
                [CallMethod_23] = struct('value', CallMethod_23, 'rank', numel(CallMethod_23_format));
            else
                [CallMethod_23] = struct('value', CallMethod_23, 'rank', int64(max([2, ndims(CallMethod_23), numel(CallMethod_23_rank)])));
            end
            if ~contains(CallMethod_24_format,'U')
                [CallMethod_24] = struct('value', CallMethod_24, 'rank', numel(CallMethod_24_format));
            else
                [CallMethod_24] = struct('value', CallMethod_24, 'rank', int64(max([2, ndims(CallMethod_24), numel(CallMethod_24_rank)])));
            end


            CallMethod_18_labelled = CallMethod_18;
            CallMethod_18_labelled.value = permute(CallMethod_18_labelled.value, fliplr(1:max(2,CallMethod_18_labelled.rank)));
            CallMethod_19_labelled = CallMethod_19;
            CallMethod_19_labelled.value = permute(CallMethod_19_labelled.value, fliplr(1:max(2,CallMethod_19_labelled.rank)));
            CallMethod_20_labelled = CallMethod_20;
            CallMethod_20_labelled.value = permute(CallMethod_20_labelled.value, fliplr(1:max(2,CallMethod_20_labelled.rank)));
            [CallMethod_30,CallMethod_30_rank] = GetAttr_0.(predict)(CallMethod_18_labelled.value,CallMethod_19_labelled.value,CallMethod_20_labelled.value,dlarray(ones(1,CallMethod_18.rank),'UU'),dlarray(ones(1,CallMethod_19.rank),'UU'),dlarray(ones(1,CallMethod_20.rank),'UU'));
            [CallMethod_30, CallMethod_30_format] = segformer_eager.ops.permuteToReversePyTorch(CallMethod_30, '', int64(numel(CallMethod_30_rank)));
            if ~contains(CallMethod_30_format,'U')
                [CallMethod_30] = struct('value', CallMethod_30, 'rank', numel(CallMethod_30_format));
            else
                [CallMethod_30] = struct('value', CallMethod_30, 'rank', int64(max([2, ndims(CallMethod_30), numel(CallMethod_30_rank)])));
            end


            CallMethod_30_labelled = CallMethod_30;
            CallMethod_30_labelled.value = permute(CallMethod_30_labelled.value, fliplr(1:max(2,CallMethod_30_labelled.rank)));
            CallMethod_21_labelled = CallMethod_21;
            CallMethod_21_labelled.value = permute(CallMethod_21_labelled.value, fliplr(1:max(2,CallMethod_21_labelled.rank)));
            CallMethod_22_labelled = CallMethod_22;
            CallMethod_22_labelled.value = permute(CallMethod_22_labelled.value, fliplr(1:max(2,CallMethod_22_labelled.rank)));
            [CallMethod_33,CallMethod_33_rank] = GetAttr_1.(predict)(CallMethod_30_labelled.value,CallMethod_21_labelled.value,CallMethod_22_labelled.value,dlarray(ones(1,CallMethod_30.rank),'UU'),dlarray(ones(1,CallMethod_21.rank),'UU'),dlarray(ones(1,CallMethod_22.rank),'UU'));
            [CallMethod_33, CallMethod_33_format] = segformer_eager.ops.permuteToReversePyTorch(CallMethod_33, '', int64(numel(CallMethod_33_rank)));
            if ~contains(CallMethod_33_format,'U')
                [CallMethod_33] = struct('value', CallMethod_33, 'rank', numel(CallMethod_33_format));
            else
                [CallMethod_33] = struct('value', CallMethod_33, 'rank', int64(max([2, ndims(CallMethod_33), numel(CallMethod_33_rank)])));
            end


            CallMethod_33_labelled = CallMethod_33;
            CallMethod_33_labelled.value = permute(CallMethod_33_labelled.value, fliplr(1:max(2,CallMethod_33_labelled.rank)));
            [CallMethod_36,CallMethod_36_rank] = GetAttr_layernorm_1.(predict)(CallMethod_33_labelled.value,dlarray(ones(1,CallMethod_33.rank),'UU'));
            [CallMethod_36, CallMethod_36_format] = segformer_eager.ops.permuteToReversePyTorch(CallMethod_36, '', int64(numel(CallMethod_36_rank)));
            if ~contains(CallMethod_36_format,'U')
                [CallMethod_36] = struct('value', CallMethod_36, 'rank', numel(CallMethod_36_format));
            else
                [CallMethod_36] = struct('value', CallMethod_36, 'rank', int64(max([2, ndims(CallMethod_36), numel(CallMethod_36_rank)])));
            end

            [size_39] = segformer_eager.ops.pySize(CallMethod_36, Constant_38);
            [NumToTensor_batchsize_1] = segformer_eager.ops.makeStructForConstant(single(size_39.value), int64([size_39.rank]), "Tensor");
            [Int_44] = segformer_eager.ops.makeStructForConstant(NumToTensor_batchsize_1.value, int64([NumToTensor_batchsize_1.rank]), "Integer");
            [ListConstruct_48] = segformer_eager.ops.pyListConstruct(Int_44, CallMethod_23, CallMethod_24, Constant_47);
            [reshape_49] = segformer_eager.ops.pyView(CallMethod_36, ListConstruct_48);
            [Constant_68] = segformer_eager.ops.makeStructForConstant(int64(obj.Constant_68), int64(1), "Typed");
            [permute_55] = segformer_eager.ops.pyPermute(reshape_49, Constant_68);
            contiguous_encoderhiddenstate_1 = permute_55;
        end

    end
end

