classdef modelingsegformer_torchmangle107_SegformerSequenceReduction < nnet.layer.Layer & nnet.layer.Formattable & ...
        nnet.layer.AutogeneratedFromPyTorch & nnet.layer.Acceleratable
    %modelingsegformer_torchmangle107_SegformerSequenceReduction Auto-generated custom layer
    % Auto-generated by MATLAB on 04-Sep-2026 18:43:48

    properties (Learnable)
        % Networks (type dlnetwork)

        Param_sequence_reduction
        Param_layer_norm
    end

    properties
        % Non-Trainable Parameters
        Constant_9
        Constant_19
        Constant_29
        Constant_43



    end

    properties (Learnable)
        % Trainable Parameters

    end

    methods
        function obj = modelingsegformer_torchmangle107_SegformerSequenceReduction(Name, Type, InputNames, OutputNames)
            obj.Name = Name;
            obj.Type = Type;
            obj.NumInputs = 6;
            obj.NumOutputs = 1;
            obj.InputNames = InputNames;
            obj.OutputNames = OutputNames;
        end

        function [CallMethod_49] = predict(obj,size_argument1_1, ListConstruct_argument2_1, ListConstruct_argument3_1, size_argument1_1_rank, ListConstruct_argument2_1_rank, ListConstruct_argument3_1_rank)

            %Use the input format inferred by the importer to permute the input into reverse-PyTorch dimension order
            [size_argument1_1, size_argument1_1_format] = segformer_eager.ops.permuteToReversePyTorch(size_argument1_1, '', numel(size_argument1_1_rank));

            %Use the input format inferred by the importer to permute the input into reverse-PyTorch dimension order
            [ListConstruct_argument2_1, ListConstruct_argument2_1_format] = segformer_eager.ops.permuteToReversePyTorch(ListConstruct_argument2_1, '', numel(ListConstruct_argument2_1_rank));

            %Use the input format inferred by the importer to permute the input into reverse-PyTorch dimension order
            [ListConstruct_argument3_1, ListConstruct_argument3_1_format] = segformer_eager.ops.permuteToReversePyTorch(ListConstruct_argument3_1, '', numel(ListConstruct_argument3_1_rank));
            [size_argument1_1] = struct('value', size_argument1_1, 'rank', int64(max([2, ndims(size_argument1_1), numel(size_argument1_1_rank)])));
            [ListConstruct_argument2_1] = struct('value', ListConstruct_argument2_1, 'rank', int64(max([2, ndims(ListConstruct_argument2_1), numel(ListConstruct_argument2_1_rank)])));
            [ListConstruct_argument3_1] = struct('value', ListConstruct_argument3_1, 'rank', int64(max([2, ndims(ListConstruct_argument3_1), numel(ListConstruct_argument3_1_rank)])));

            [CallMethod_49] = tracedPyTorchFunction(obj,size_argument1_1, ListConstruct_argument2_1, ListConstruct_argument3_1,false,"predict");


            %Permute U-labelled output to forward PyTorch dimension ordering
            if(isa(CallMethod_49.value,'dlarray') && any(dims(CallMethod_49.value) == 'U'))
                CallMethod_49 = permute(CallMethod_49.value, fliplr(1:max(2,CallMethod_49.rank)));
            else
                CallMethod_49 = dlarray(single(CallMethod_49.value), 'UU');
            end

        end



        function [CallMethod_49] = forward(obj,size_argument1_1, ListConstruct_argument2_1, ListConstruct_argument3_1, size_argument1_1_rank, ListConstruct_argument2_1_rank, ListConstruct_argument3_1_rank)

            %Use the input format inferred by the importer to permute the input into reverse-PyTorch dimension order
            [size_argument1_1, size_argument1_1_format] = segformer_eager.ops.permuteToReversePyTorch(size_argument1_1, '', numel(size_argument1_1_rank));

            %Use the input format inferred by the importer to permute the input into reverse-PyTorch dimension order
            [ListConstruct_argument2_1, ListConstruct_argument2_1_format] = segformer_eager.ops.permuteToReversePyTorch(ListConstruct_argument2_1, '', numel(ListConstruct_argument2_1_rank));

            %Use the input format inferred by the importer to permute the input into reverse-PyTorch dimension order
            [ListConstruct_argument3_1, ListConstruct_argument3_1_format] = segformer_eager.ops.permuteToReversePyTorch(ListConstruct_argument3_1, '', numel(ListConstruct_argument3_1_rank));
            [size_argument1_1] = struct('value', size_argument1_1, 'rank', int64(max([2, ndims(size_argument1_1), numel(size_argument1_1_rank)])));
            [ListConstruct_argument2_1] = struct('value', ListConstruct_argument2_1, 'rank', int64(max([2, ndims(ListConstruct_argument2_1), numel(ListConstruct_argument2_1_rank)])));
            [ListConstruct_argument3_1] = struct('value', ListConstruct_argument3_1, 'rank', int64(max([2, ndims(ListConstruct_argument3_1), numel(ListConstruct_argument3_1_rank)])));

            [CallMethod_49] = tracedPyTorchFunction(obj,size_argument1_1, ListConstruct_argument2_1, ListConstruct_argument3_1,true,"forward");


            %Permute U-labelled output to forward PyTorch dimension ordering
            if(isa(CallMethod_49.value,'dlarray') && any(dims(CallMethod_49.value) == 'U'))
                CallMethod_49 = permute(CallMethod_49.value, fliplr(1:max(2,CallMethod_49.rank)));
            else
                CallMethod_49 = dlarray(single(CallMethod_49.value), 'UU');
            end

        end



        function [CallMethod_49] = tracedPyTorchFunction(obj,size_argument1_1, ListConstruct_argument2_1, ListConstruct_argument3_1,isForward,predict)

            [Constant_9] = segformer_eager.ops.makeStructForConstant(int64(obj.Constant_9), int64(0), "Typed");
            [Constant_19] = segformer_eager.ops.makeStructForConstant(int64(obj.Constant_19), int64(0), "Typed");
            [Constant_29] = segformer_eager.ops.makeStructForConstant(int64(obj.Constant_29), int64(0), "Typed");
            [Constant_43] = segformer_eager.ops.makeStructForConstant(int64(obj.Constant_43), int64(0), "Typed");
            GetAttr_layernorm_1 = obj.Param_layer_norm;


            GetAttr_sequencereduction_1 = obj.Param_sequence_reduction;

            GetAttr_sequencereduction_1_InputFormat1 = 'BCSS';

            [size_10] = segformer_eager.ops.pySize(size_argument1_1, Constant_9);
            [NumToTensor_batchsize_1] = segformer_eager.ops.makeStructForConstant(single(size_10.value), int64([size_10.rank]), "Tensor");
            [Int_14] = segformer_eager.ops.makeStructForConstant(NumToTensor_batchsize_1.value, int64([NumToTensor_batchsize_1.rank]), "Integer");
            [Int_17] = segformer_eager.ops.makeStructForConstant(NumToTensor_batchsize_1.value, int64([NumToTensor_batchsize_1.rank]), "Integer");
            [size_20] = segformer_eager.ops.pySize(size_argument1_1, Constant_19);
            [NumToTensor_numchannels_1] = segformer_eager.ops.makeStructForConstant(single(size_20.value), int64([size_20.rank]), "Tensor");
            [Int_24] = segformer_eager.ops.makeStructForConstant(NumToTensor_numchannels_1.value, int64([NumToTensor_numchannels_1.rank]), "Integer");
            [Int_27] = segformer_eager.ops.makeStructForConstant(NumToTensor_numchannels_1.value, int64([NumToTensor_numchannels_1.rank]), "Integer");
            [transpose_30] = segformer_eager.ops.pyTranspose(size_argument1_1, Constant_29, Constant_19);
            % See segformer_modelingsegformer_SegformerSequenceReduction.m for the
            % full explanation: H/W and batch/channels arrive corrupted from
            % dlnetwork's own dispatch (nondeterministically across repeated
            % predict() calls on the same layer). Derive all four directly from
            % size_argument1_1/transpose_30's actual MATLAB storage instead.
            batchVal = 1;
            chanVal = size(size_argument1_1.value, 1);
            Int_14.value = int64(batchVal);
            Int_17.value = int64(batchVal);
            Int_24.value = int64(chanVal);
            Int_27.value = int64(chanVal);
            hw = numel(transpose_30.value) / (batchVal * chanVal);
            hwSide = round(sqrt(hw));
            if hwSide * hwSide ~= hw
                error('SegformerSequenceReduction:NonSquarePatch', ...
                    'Derived H*W=%g is not a perfect square (H=W assumption requires square input patches).', hw);
            end
            heightFixed = ListConstruct_argument2_1; heightFixed.value = int64(hwSide);
            widthFixed = ListConstruct_argument3_1; widthFixed.value = int64(hwSide);
            [ListConstruct_35] = segformer_eager.ops.pyListConstruct(Int_17, Int_27, heightFixed, widthFixed);
            [reshape_input_1] = segformer_eager.ops.pyView(transpose_30, ListConstruct_35);

            [reshape_input_1_labelled] = segformer_eager.ops.labelWithPropagatedFormats(reshape_input_1, GetAttr_sequencereduction_1_InputFormat1);
            [CallMethod_39] = GetAttr_sequencereduction_1.(predict)(reshape_input_1_labelled.value);
            [CallMethod_39, CallMethod_39_format] = segformer_eager.ops.permuteToReversePyTorch(CallMethod_39, 'BCSS', '');
            if ~contains(CallMethod_39_format,'U')
                [CallMethod_39] = struct('value', CallMethod_39, 'rank', numel(CallMethod_39_format));
            else
                [CallMethod_39] = struct('value', CallMethod_39, 'rank', '');
            end

            [ListConstruct_44] = segformer_eager.ops.pyListConstruct(Int_14, Int_24, Constant_43);
            [reshape_45] = segformer_eager.ops.pyView(CallMethod_39, ListConstruct_44);
            [transpose_input0_1] = segformer_eager.ops.pyTranspose(reshape_45, Constant_29, Constant_19);

            transpose_input0_1_labelled = transpose_input0_1;
            transpose_input0_1_labelled.value = permute(transpose_input0_1_labelled.value, fliplr(1:max(2,transpose_input0_1_labelled.rank)));
            [CallMethod_49] = GetAttr_layernorm_1.(predict)(transpose_input0_1_labelled.value);
            [CallMethod_49, CallMethod_49_format] = segformer_eager.ops.permuteToReversePyTorch(CallMethod_49, '', int64(3));
            if ~contains(CallMethod_49_format,'U')
                [CallMethod_49] = struct('value', CallMethod_49, 'rank', numel(CallMethod_49_format));
            else
                [CallMethod_49] = struct('value', CallMethod_49, 'rank', int64(3));
            end

        end

    end
end

