classdef modelingsegformer_torchmangle93_SegformerDepthWiseConv < nnet.layer.Layer & nnet.layer.Formattable & ...
        nnet.layer.AutogeneratedFromPyTorch & nnet.layer.Acceleratable
    %modelingsegformer_torchmangle93_SegformerDepthWiseConv Auto-generated custom layer
    % Auto-generated by MATLAB on 04-Sep-2026 18:43:47

    properties (Learnable)
        % Networks (type dlnetwork)

        Param_dwconv
    end

    properties
        % Non-Trainable Parameters
        Constant_32
        Constant_7
        Constant_14
        Constant_21



    end

    properties (Learnable)
        % Trainable Parameters

    end

    methods
        function obj = modelingsegformer_torchmangle93_SegformerDepthWiseConv(Name, Type, InputNames, OutputNames)
            obj.Name = Name;
            obj.Type = Type;
            obj.NumInputs = 6;
            obj.NumOutputs = 2;
            obj.InputNames = InputNames;
            obj.OutputNames = OutputNames;
        end

        function [transpose_35, transpose_35_rank] = predict(obj,size_argument1_1, ListConstruct_argument2_1, ListConstruct_argument3_1, size_argument1_1_rank, ListConstruct_argument2_1_rank, ListConstruct_argument3_1_rank)

            %Use the input format inferred by the importer to permute the input into reverse-PyTorch dimension order
            [size_argument1_1, size_argument1_1_format] = segformer_eager.ops.permuteToReversePyTorch(size_argument1_1, '', numel(size_argument1_1_rank));

            %Use the input format inferred by the importer to permute the input into reverse-PyTorch dimension order
            [ListConstruct_argument2_1, ListConstruct_argument2_1_format] = segformer_eager.ops.permuteToReversePyTorch(ListConstruct_argument2_1, '', numel(ListConstruct_argument2_1_rank));

            %Use the input format inferred by the importer to permute the input into reverse-PyTorch dimension order
            [ListConstruct_argument3_1, ListConstruct_argument3_1_format] = segformer_eager.ops.permuteToReversePyTorch(ListConstruct_argument3_1, '', numel(ListConstruct_argument3_1_rank));
            [size_argument1_1] = struct('value', size_argument1_1, 'rank', int64(max([2, ndims(size_argument1_1), numel(size_argument1_1_rank)])));
            [ListConstruct_argument2_1] = struct('value', ListConstruct_argument2_1, 'rank', int64(max([2, ndims(ListConstruct_argument2_1), numel(ListConstruct_argument2_1_rank)])));
            [ListConstruct_argument3_1] = struct('value', ListConstruct_argument3_1, 'rank', int64(max([2, ndims(ListConstruct_argument3_1), numel(ListConstruct_argument3_1_rank)])));

            [transpose_35] = tracedPyTorchFunction(obj,size_argument1_1, ListConstruct_argument2_1, ListConstruct_argument3_1,false,"predict");

            [transpose_35_rank] = ones([1,transpose_35.rank], 'single');
            transpose_35_rank = dlarray(transpose_35_rank,'UU');
            %Permute U-labelled output to forward PyTorch dimension ordering
            if(isa(transpose_35.value,'dlarray') && any(dims(transpose_35.value) == 'U'))
                transpose_35 = permute(transpose_35.value, fliplr(1:max(2,transpose_35.rank)));
            else
                transpose_35 = dlarray(single(transpose_35.value), 'UU');
            end

        end



        function [transpose_35, transpose_35_rank] = forward(obj,size_argument1_1, ListConstruct_argument2_1, ListConstruct_argument3_1, size_argument1_1_rank, ListConstruct_argument2_1_rank, ListConstruct_argument3_1_rank)

            %Use the input format inferred by the importer to permute the input into reverse-PyTorch dimension order
            [size_argument1_1, size_argument1_1_format] = segformer_eager.ops.permuteToReversePyTorch(size_argument1_1, '', numel(size_argument1_1_rank));

            %Use the input format inferred by the importer to permute the input into reverse-PyTorch dimension order
            [ListConstruct_argument2_1, ListConstruct_argument2_1_format] = segformer_eager.ops.permuteToReversePyTorch(ListConstruct_argument2_1, '', numel(ListConstruct_argument2_1_rank));

            %Use the input format inferred by the importer to permute the input into reverse-PyTorch dimension order
            [ListConstruct_argument3_1, ListConstruct_argument3_1_format] = segformer_eager.ops.permuteToReversePyTorch(ListConstruct_argument3_1, '', numel(ListConstruct_argument3_1_rank));
            [size_argument1_1] = struct('value', size_argument1_1, 'rank', int64(max([2, ndims(size_argument1_1), numel(size_argument1_1_rank)])));
            [ListConstruct_argument2_1] = struct('value', ListConstruct_argument2_1, 'rank', int64(max([2, ndims(ListConstruct_argument2_1), numel(ListConstruct_argument2_1_rank)])));
            [ListConstruct_argument3_1] = struct('value', ListConstruct_argument3_1, 'rank', int64(max([2, ndims(ListConstruct_argument3_1), numel(ListConstruct_argument3_1_rank)])));

            [transpose_35] = tracedPyTorchFunction(obj,size_argument1_1, ListConstruct_argument2_1, ListConstruct_argument3_1,true,"forward");

            [transpose_35_rank] = ones([1,transpose_35.rank], 'single');
            transpose_35_rank = dlarray(transpose_35_rank,'UU');
            %Permute U-labelled output to forward PyTorch dimension ordering
            if(isa(transpose_35.value,'dlarray') && any(dims(transpose_35.value) == 'U'))
                transpose_35 = permute(transpose_35.value, fliplr(1:max(2,transpose_35.rank)));
            else
                transpose_35 = dlarray(single(transpose_35.value), 'UU');
            end

        end



        function [transpose_35] = tracedPyTorchFunction(obj,size_argument1_1, ListConstruct_argument2_1, ListConstruct_argument3_1,isForward,predict)

            [Constant_32] = segformer_eager.ops.makeStructForConstant(int64(obj.Constant_32), int64(0), "Typed");
            [Constant_7] = segformer_eager.ops.makeStructForConstant(int64(obj.Constant_7), int64(0), "Typed");
            [Constant_14] = segformer_eager.ops.makeStructForConstant(int64(obj.Constant_14), int64(0), "Typed");
            [Constant_21] = segformer_eager.ops.makeStructForConstant(int64(obj.Constant_21), int64(0), "Typed");
            GetAttr_dwconv_1 = obj.Param_dwconv;

            GetAttr_dwconv_1_InputFormat1 = 'BCSS';

            [size_8] = segformer_eager.ops.pySize(size_argument1_1, Constant_7);
            [NumToTensor_batchsize_1] = segformer_eager.ops.makeStructForConstant(single(size_8.value), int64([size_8.rank]), "Tensor");
            [Int_12] = segformer_eager.ops.makeStructForConstant(NumToTensor_batchsize_1.value, int64([NumToTensor_batchsize_1.rank]), "Integer");
            [size_15] = segformer_eager.ops.pySize(size_argument1_1, Constant_14);
            [NumToTensor_numchannels_1] = segformer_eager.ops.makeStructForConstant(single(size_15.value), int64([size_15.rank]), "Tensor");
            [Int_19] = segformer_eager.ops.makeStructForConstant(NumToTensor_numchannels_1.value, int64([NumToTensor_numchannels_1.rank]), "Integer");
            [transpose_22] = segformer_eager.ops.pyTranspose(size_argument1_1, Constant_21, Constant_14);
            % See segformer_modelingsegformer_SegformerDepthWiseConv.m for the
            % full explanation: H/W and batch/channels arrive corrupted from
            % dlnetwork's own dispatch. Derive all four directly from
            % size_argument1_1/transpose_22's actual MATLAB storage instead.
            batchVal = 1;
            chanVal = size(size_argument1_1.value, 1);
            Int_12.value = int64(batchVal);
            Int_19.value = int64(chanVal);
            hw = numel(transpose_22.value) / (batchVal * chanVal);
            hwSide = round(sqrt(hw));
            if hwSide * hwSide ~= hw
                error('SegformerDepthWiseConv:NonSquarePatch', ...
                    'Derived H*W=%g is not a perfect square (H=W assumption requires square input patches).', hw);
            end
            heightFixed = ListConstruct_argument2_1; heightFixed.value = int64(hwSide);
            widthFixed = ListConstruct_argument3_1; widthFixed.value = int64(hwSide);
            [ListConstruct_27] = segformer_eager.ops.pyListConstruct(Int_12, Int_19, heightFixed, widthFixed);
            [view_input_1] = segformer_eager.ops.pyView(transpose_22, ListConstruct_27);

            [view_input_1_labelled] = segformer_eager.ops.labelWithPropagatedFormats(view_input_1, GetAttr_dwconv_1_InputFormat1);
            [CallMethod_31] = GetAttr_dwconv_1.(predict)(view_input_1_labelled.value);
            [CallMethod_31, CallMethod_31_format] = segformer_eager.ops.permuteToReversePyTorch(CallMethod_31, 'BCSS', '');
            if ~contains(CallMethod_31_format,'U')
                [CallMethod_31] = struct('value', CallMethod_31, 'rank', numel(CallMethod_31_format));
            else
                [CallMethod_31] = struct('value', CallMethod_31, 'rank', '');
            end

            [flatten_33] = segformer_eager.ops.pyFlatten(CallMethod_31, Constant_14, Constant_32);
            [transpose_35] = segformer_eager.ops.pyTranspose(flatten_33, Constant_21, Constant_14);
        end

    end
end

