classdef modelingsegformer_torchmangle131_SegformerAttention < nnet.layer.Layer & nnet.layer.Formattable & ...
        nnet.layer.AutogeneratedFromPyTorch
    %modelingsegformer_torchmangle131_SegformerAttention Auto-generated custom layer
    % Auto-generated by MATLAB on 04-Sep-2026 18:43:53

    properties (Learnable)
        % Networks (type dlnetwork)

        Param_q_proj
        Param_k_proj
        Param_v_proj
        Param_o_proj
    end

    properties
        % Non-Trainable Parameters
        Constant_91
        Constant_89
        Constant_84
        Constant_11
        Constant_21
        Constant_35
        Constant_36
        Constant_40
        Constant_80
        Constant_87
        Constant_94



    end

    properties (Learnable)
        % Trainable Parameters

    end

    methods
        function obj = modelingsegformer_torchmangle131_SegformerAttention(Name, Type, InputNames, OutputNames)
            obj.Name = Name;
            obj.Type = Type;
            obj.NumInputs = 2;
            obj.NumOutputs = 2;
            obj.InputNames = InputNames;
            obj.OutputNames = OutputNames;
        end

        function [CallMethod_114, CallMethod_114_rank] = predict(obj,size_argument1_1, size_argument1_1_rank)

            %Use the input format inferred by the importer to permute the input into reverse-PyTorch dimension order
            [size_argument1_1, size_argument1_1_format] = segformer_eager.ops.permuteToReversePyTorch(size_argument1_1, '', numel(size_argument1_1_rank));
            [size_argument1_1] = struct('value', size_argument1_1, 'rank', int64(max([2, ndims(size_argument1_1), numel(size_argument1_1_rank)])));

            [CallMethod_114] = tracedPyTorchFunction(obj,size_argument1_1,false,"predict");

            [CallMethod_114_rank] = ones([1,CallMethod_114.rank], 'single');
            CallMethod_114_rank = dlarray(CallMethod_114_rank,'UU');
            %Permute U-labelled output to forward PyTorch dimension ordering
            if(isa(CallMethod_114.value,'dlarray') && any(dims(CallMethod_114.value) == 'U'))
                CallMethod_114 = permute(CallMethod_114.value, fliplr(1:max(2,CallMethod_114.rank)));
            else
                CallMethod_114 = dlarray(single(CallMethod_114.value), 'UU');
            end

        end



        function [CallMethod_114, CallMethod_114_rank] = forward(obj,size_argument1_1, size_argument1_1_rank)

            %Use the input format inferred by the importer to permute the input into reverse-PyTorch dimension order
            [size_argument1_1, size_argument1_1_format] = segformer_eager.ops.permuteToReversePyTorch(size_argument1_1, '', numel(size_argument1_1_rank));
            [size_argument1_1] = struct('value', size_argument1_1, 'rank', int64(max([2, ndims(size_argument1_1), numel(size_argument1_1_rank)])));

            [CallMethod_114] = tracedPyTorchFunction(obj,size_argument1_1,true,"forward");

            [CallMethod_114_rank] = ones([1,CallMethod_114.rank], 'single');
            CallMethod_114_rank = dlarray(CallMethod_114_rank,'UU');
            %Permute U-labelled output to forward PyTorch dimension ordering
            if(isa(CallMethod_114.value,'dlarray') && any(dims(CallMethod_114.value) == 'U'))
                CallMethod_114 = permute(CallMethod_114.value, fliplr(1:max(2,CallMethod_114.rank)));
            else
                CallMethod_114 = dlarray(single(CallMethod_114.value), 'UU');
            end

        end



        function [CallMethod_114] = tracedPyTorchFunction(obj,size_argument1_1,isForward,predict)

            [Constant_91] = segformer_eager.ops.makeStructForConstant(double(obj.Constant_91), int64(0), "Typed");
            [Constant_89] = segformer_eager.ops.makeStructForConstant(int64(obj.Constant_89), int64(0), "Typed");
            [Constant_84] = segformer_eager.ops.makeStructForConstant(single(obj.Constant_84), int64([0]), "Tensor");
            [Constant_11] = segformer_eager.ops.makeStructForConstant(int64(obj.Constant_11), int64(0), "Typed");
            [Constant_21] = segformer_eager.ops.makeStructForConstant(int64(obj.Constant_21), int64(0), "Typed");
            [Constant_35] = segformer_eager.ops.makeStructForConstant(int64(obj.Constant_35), int64(0), "Typed");
            [Constant_36] = segformer_eager.ops.makeStructForConstant(int64(obj.Constant_36), int64(0), "Typed");
            [Constant_40] = segformer_eager.ops.makeStructForConstant(int64(obj.Constant_40), int64(0), "Typed");
            [Constant_80] = segformer_eager.ops.makeStructForConstant(int64(obj.Constant_80), int64(0), "Typed");
            [Constant_87] = segformer_eager.ops.makeStructForConstant(int64(obj.Constant_87), int64(0), "Typed");
            [Constant_94] = segformer_eager.ops.makeStructForConstant(single(obj.Constant_94), int64(0), "Typed");
            GetAttr_oproj_1 = obj.Param_o_proj;


            GetAttr_vproj_1 = obj.Param_v_proj;


            GetAttr_kproj_1 = obj.Param_k_proj;


            GetAttr_qproj_1 = obj.Param_q_proj;


            [size_12] = segformer_eager.ops.pySize(size_argument1_1, Constant_11);
            [NumToTensor_13] = segformer_eager.ops.makeStructForConstant(single(size_12.value), int64([size_12.rank]), "Tensor");
            [Int_16] = segformer_eager.ops.makeStructForConstant(NumToTensor_13.value, int64([NumToTensor_13.rank]), "Integer");
            [Int_19] = segformer_eager.ops.makeStructForConstant(NumToTensor_13.value, int64([NumToTensor_13.rank]), "Integer");
            [size_22] = segformer_eager.ops.pySize(size_argument1_1, Constant_21);
            [NumToTensor_23] = segformer_eager.ops.makeStructForConstant(single(size_22.value), int64([size_22.rank]), "Tensor");
            [Int_26] = segformer_eager.ops.makeStructForConstant(NumToTensor_23.value, int64([NumToTensor_23.rank]), "Integer");
            [Int_29] = segformer_eager.ops.makeStructForConstant(NumToTensor_23.value, int64([NumToTensor_23.rank]), "Integer");

            % Int_19/Int_29 (query), Int_50/Int_59 (key), Int_47/Int_56 (value)
            % are batch/seq via pySize on size_argument1_1 - unreliable on this
            % squeezed-batch tensor, same root cause documented in
            % SegformerSequenceReduction.m. This variant has sr_ratio=1 (no
            % sequence reduction), so Q/K/V all share the same size_argument1_1
            % source; batch is always 1, seq_len from its raw storage shape.
            Int_19.value = int64(1);
            Int_29.value = int64(size(size_argument1_1.value, 2));

            size_argument1_1_labelled = size_argument1_1;
            size_argument1_1_labelled.value = permute(size_argument1_1_labelled.value, fliplr(1:max(2,size_argument1_1_labelled.rank)));
            [CallMethod_32,CallMethod_32_rank] = GetAttr_qproj_1.(predict)(size_argument1_1_labelled.value,dlarray(ones(1,size_argument1_1.rank),'UU'));
            [CallMethod_32, CallMethod_32_format] = segformer_eager.ops.permuteToReversePyTorch(CallMethod_32, '', int64(numel(CallMethod_32_rank)));
            if ~contains(CallMethod_32_format,'U')
                [CallMethod_32] = struct('value', CallMethod_32, 'rank', numel(CallMethod_32_format));
            else
                [CallMethod_32] = struct('value', CallMethod_32, 'rank', int64(max([2, ndims(CallMethod_32), numel(CallMethod_32_rank)])));
            end

            [ListConstruct_37] = segformer_eager.ops.pyListConstruct(Int_19, Int_29, Constant_35, Constant_36);
            [view_38] = segformer_eager.ops.pyView(CallMethod_32, ListConstruct_37);
            [transpose_query_1] = segformer_eager.ops.pyTranspose(view_38, Constant_21, Constant_40);
            [size_43] = segformer_eager.ops.pySize(size_argument1_1, Constant_11);
            [NumToTensor_44] = segformer_eager.ops.makeStructForConstant(single(size_43.value), int64([size_43.rank]), "Tensor");
            [Int_47] = segformer_eager.ops.makeStructForConstant(NumToTensor_44.value, int64([NumToTensor_44.rank]), "Integer");
            [Int_50] = segformer_eager.ops.makeStructForConstant(NumToTensor_44.value, int64([NumToTensor_44.rank]), "Integer");
            [size_52] = segformer_eager.ops.pySize(size_argument1_1, Constant_21);
            [NumToTensor_53] = segformer_eager.ops.makeStructForConstant(single(size_52.value), int64([size_52.rank]), "Tensor");
            [Int_56] = segformer_eager.ops.makeStructForConstant(NumToTensor_53.value, int64([NumToTensor_53.rank]), "Integer");
            [Int_59] = segformer_eager.ops.makeStructForConstant(NumToTensor_53.value, int64([NumToTensor_53.rank]), "Integer");

            Int_47.value = int64(1);
            Int_56.value = int64(size(size_argument1_1.value, 2));
            Int_50.value = int64(1);
            Int_59.value = int64(size(size_argument1_1.value, 2));

            size_argument1_1_labelled = size_argument1_1;
            size_argument1_1_labelled.value = permute(size_argument1_1_labelled.value, fliplr(1:max(2,size_argument1_1_labelled.rank)));
            [CallMethod_62,CallMethod_62_rank] = GetAttr_kproj_1.(predict)(size_argument1_1_labelled.value,dlarray(ones(1,size_argument1_1.rank),'UU'));
            [CallMethod_62, CallMethod_62_format] = segformer_eager.ops.permuteToReversePyTorch(CallMethod_62, '', int64(numel(CallMethod_62_rank)));
            if ~contains(CallMethod_62_format,'U')
                [CallMethod_62] = struct('value', CallMethod_62, 'rank', numel(CallMethod_62_format));
            else
                [CallMethod_62] = struct('value', CallMethod_62, 'rank', int64(max([2, ndims(CallMethod_62), numel(CallMethod_62_rank)])));
            end

            [ListConstruct_65] = segformer_eager.ops.pyListConstruct(Int_50, Int_59, Constant_35, Constant_36);
            [view_66] = segformer_eager.ops.pyView(CallMethod_62, ListConstruct_65);
            [transpose_key_1] = segformer_eager.ops.pyTranspose(view_66, Constant_21, Constant_40);

            size_argument1_1_labelled = size_argument1_1;
            size_argument1_1_labelled.value = permute(size_argument1_1_labelled.value, fliplr(1:max(2,size_argument1_1_labelled.rank)));
            [CallMethod_71,CallMethod_71_rank] = GetAttr_vproj_1.(predict)(size_argument1_1_labelled.value,dlarray(ones(1,size_argument1_1.rank),'UU'));
            [CallMethod_71, CallMethod_71_format] = segformer_eager.ops.permuteToReversePyTorch(CallMethod_71, '', int64(numel(CallMethod_71_rank)));
            if ~contains(CallMethod_71_format,'U')
                [CallMethod_71] = struct('value', CallMethod_71, 'rank', numel(CallMethod_71_format));
            else
                [CallMethod_71] = struct('value', CallMethod_71, 'rank', int64(max([2, ndims(CallMethod_71), numel(CallMethod_71_rank)])));
            end

            [ListConstruct_74] = segformer_eager.ops.pyListConstruct(Int_47, Int_56, Constant_35, Constant_36);
            [view_75] = segformer_eager.ops.pyView(CallMethod_71, ListConstruct_74);
            [transpose_value_1] = segformer_eager.ops.pyTranspose(view_75, Constant_21, Constant_40);
            [transpose_81] = segformer_eager.ops.pyTranspose(transpose_key_1, Constant_40, Constant_80);
            [matmul_82] = segformer_eager.ops.pyMatmul(transpose_query_1, transpose_81);
            [mul_input_1] = segformer_eager.ops.pyElementwiseBinary(matmul_82, Constant_84, 'times');
            [softmax_88] = segformer_eager.ops.pySoftmax(mul_input_1, Constant_35);
            [to_input0_1] = segformer_eager.ops.pyToUnary(softmax_88, Constant_87, Constant_89, Constant_89, Constant_91);
            [dropout_attnweights_1] = segformer_eager.ops.pyDropout(to_input0_1, Constant_94, isForward);
            [matmul_attnoutput_1] = segformer_eager.ops.pyMatmul(dropout_attnweights_1, transpose_value_1);
            [transpose_101] = segformer_eager.ops.pyTranspose(matmul_attnoutput_1, Constant_21, Constant_40);
            contiguous_attnoutput0_1 = transpose_101;
            % Final head-merge reshape: Int_16/Int_26 (batch/channels via pySize
            % on size_argument1_1) are unreliable on this squeezed-batch tensor -
            % same root cause documented in SegformerSequenceReduction.m. batch is
            % always 1; seq_len derived directly from size_argument1_1 storage.
            Int_16.value = int64(1);
            Int_26.value = int64(size(size_argument1_1.value, 2));
            [ListConstruct_107] = segformer_eager.ops.pyListConstruct(Int_16, Int_26, Constant_35);
            [reshape_108] = segformer_eager.ops.pyView(contiguous_attnoutput0_1, ListConstruct_107);
            contiguous_input1_1 = reshape_108;

            contiguous_input1_1_labelled = contiguous_input1_1;
            contiguous_input1_1_labelled.value = permute(contiguous_input1_1_labelled.value, fliplr(1:max(2,contiguous_input1_1_labelled.rank)));
            [CallMethod_114,CallMethod_114_rank] = GetAttr_oproj_1.(predict)(contiguous_input1_1_labelled.value,dlarray(ones(1,contiguous_input1_1.rank),'UU'));
            [CallMethod_114, CallMethod_114_format] = segformer_eager.ops.permuteToReversePyTorch(CallMethod_114, '', int64(numel(CallMethod_114_rank)));
            if ~contains(CallMethod_114_format,'U')
                [CallMethod_114] = struct('value', CallMethod_114, 'rank', numel(CallMethod_114_format));
            else
                [CallMethod_114] = struct('value', CallMethod_114, 'rank', int64(max([2, ndims(CallMethod_114), numel(CallMethod_114_rank)])));
            end

        end

    end
end

