classdef modelingsegformer_torchmangle79_SegformerOverlapPatchEmbeddings < nnet.layer.Layer & nnet.layer.Formattable & ...
        nnet.layer.AutogeneratedFromPyTorch & nnet.layer.Acceleratable
    %modelingsegformer_torchmangle79_SegformerOverlapPatchEmbeddings Auto-generated custom layer
    % Auto-generated by MATLAB on 04-Sep-2026 18:43:45

    properties (Learnable)
        % Networks (type dlnetwork)

        Param_proj
        Param_layer_norm
    end

    properties
        % Non-Trainable Parameters
        Constant_48
        Constant_10
        Constant_29
        Constant_50



    end

    properties (Learnable)
        % Trainable Parameters

    end

    methods
        function obj = modelingsegformer_torchmangle79_SegformerOverlapPatchEmbeddings(Name, Type, InputNames, OutputNames)
            obj.Name = Name;
            obj.Type = Type;
            obj.NumInputs = 1;
            obj.NumOutputs = 22;
            obj.InputNames = InputNames;
            obj.OutputNames = OutputNames;
        end

        function [CallMethod_54, Int_27, Int_46, Int_24, Int_43, Int_21, Int_40, Int_18, Int_37, Int_15, Int_34, CallMethod_54_rank, Int_27_rank, Int_46_rank, Int_24_rank, Int_43_rank, Int_21_rank, Int_40_rank, Int_18_rank, Int_37_rank, Int_15_rank, Int_34_rank] = predict(obj,CallMethod_argument1_1)

            %Use the input format inferred by the importer to permute the input into reverse-PyTorch dimension order
            [CallMethod_argument1_1, CallMethod_argument1_1_format] = segformer_eager.ops.permuteToReversePyTorch(CallMethod_argument1_1, '*CSS', '');

            if ~contains(CallMethod_argument1_1_format,'U')
                [CallMethod_argument1_1] = struct('value', CallMethod_argument1_1, 'rank', numel(CallMethod_argument1_1_format));
            end

            [CallMethod_54, Int_27, Int_46, Int_24, Int_43, Int_21, Int_40, Int_18, Int_37, Int_15, Int_34] = tracedPyTorchFunction(obj,CallMethod_argument1_1,false,"predict");

            [CallMethod_54_rank] = ones([1,CallMethod_54.rank], 'single');
            CallMethod_54_rank = dlarray(CallMethod_54_rank,'UU');
            %Permute U-labelled output to forward PyTorch dimension ordering
            if(isa(CallMethod_54.value,'dlarray') && any(dims(CallMethod_54.value) == 'U'))
                CallMethod_54 = permute(CallMethod_54.value, fliplr(1:max(2,CallMethod_54.rank)));
            else
                CallMethod_54 = dlarray(single(CallMethod_54.value), 'UU');
            end
            [Int_27_rank] = ones([1,Int_27.rank], 'single');
            Int_27_rank = dlarray(Int_27_rank,'UU');
            %Permute U-labelled output to forward PyTorch dimension ordering
            if(isa(Int_27.value,'dlarray') && any(dims(Int_27.value) == 'U'))
                Int_27 = permute(Int_27.value, fliplr(1:max(2,Int_27.rank)));
            else
                Int_27 = dlarray(single(Int_27.value), 'UU');
            end
            [Int_46_rank] = ones([1,Int_46.rank], 'single');
            Int_46_rank = dlarray(Int_46_rank,'UU');
            %Permute U-labelled output to forward PyTorch dimension ordering
            if(isa(Int_46.value,'dlarray') && any(dims(Int_46.value) == 'U'))
                Int_46 = permute(Int_46.value, fliplr(1:max(2,Int_46.rank)));
            else
                Int_46 = dlarray(single(Int_46.value), 'UU');
            end
            [Int_24_rank] = ones([1,Int_24.rank], 'single');
            Int_24_rank = dlarray(Int_24_rank,'UU');
            %Permute U-labelled output to forward PyTorch dimension ordering
            if(isa(Int_24.value,'dlarray') && any(dims(Int_24.value) == 'U'))
                Int_24 = permute(Int_24.value, fliplr(1:max(2,Int_24.rank)));
            else
                Int_24 = dlarray(single(Int_24.value), 'UU');
            end
            [Int_43_rank] = ones([1,Int_43.rank], 'single');
            Int_43_rank = dlarray(Int_43_rank,'UU');
            %Permute U-labelled output to forward PyTorch dimension ordering
            if(isa(Int_43.value,'dlarray') && any(dims(Int_43.value) == 'U'))
                Int_43 = permute(Int_43.value, fliplr(1:max(2,Int_43.rank)));
            else
                Int_43 = dlarray(single(Int_43.value), 'UU');
            end
            [Int_21_rank] = ones([1,Int_21.rank], 'single');
            Int_21_rank = dlarray(Int_21_rank,'UU');
            %Permute U-labelled output to forward PyTorch dimension ordering
            if(isa(Int_21.value,'dlarray') && any(dims(Int_21.value) == 'U'))
                Int_21 = permute(Int_21.value, fliplr(1:max(2,Int_21.rank)));
            else
                Int_21 = dlarray(single(Int_21.value), 'UU');
            end
            [Int_40_rank] = ones([1,Int_40.rank], 'single');
            Int_40_rank = dlarray(Int_40_rank,'UU');
            %Permute U-labelled output to forward PyTorch dimension ordering
            if(isa(Int_40.value,'dlarray') && any(dims(Int_40.value) == 'U'))
                Int_40 = permute(Int_40.value, fliplr(1:max(2,Int_40.rank)));
            else
                Int_40 = dlarray(single(Int_40.value), 'UU');
            end
            [Int_18_rank] = ones([1,Int_18.rank], 'single');
            Int_18_rank = dlarray(Int_18_rank,'UU');
            %Permute U-labelled output to forward PyTorch dimension ordering
            if(isa(Int_18.value,'dlarray') && any(dims(Int_18.value) == 'U'))
                Int_18 = permute(Int_18.value, fliplr(1:max(2,Int_18.rank)));
            else
                Int_18 = dlarray(single(Int_18.value), 'UU');
            end
            [Int_37_rank] = ones([1,Int_37.rank], 'single');
            Int_37_rank = dlarray(Int_37_rank,'UU');
            %Permute U-labelled output to forward PyTorch dimension ordering
            if(isa(Int_37.value,'dlarray') && any(dims(Int_37.value) == 'U'))
                Int_37 = permute(Int_37.value, fliplr(1:max(2,Int_37.rank)));
            else
                Int_37 = dlarray(single(Int_37.value), 'UU');
            end
            [Int_15_rank] = ones([1,Int_15.rank], 'single');
            Int_15_rank = dlarray(Int_15_rank,'UU');
            %Permute U-labelled output to forward PyTorch dimension ordering
            if(isa(Int_15.value,'dlarray') && any(dims(Int_15.value) == 'U'))
                Int_15 = permute(Int_15.value, fliplr(1:max(2,Int_15.rank)));
            else
                Int_15 = dlarray(single(Int_15.value), 'UU');
            end
            [Int_34_rank] = ones([1,Int_34.rank], 'single');
            Int_34_rank = dlarray(Int_34_rank,'UU');
            %Permute U-labelled output to forward PyTorch dimension ordering
            if(isa(Int_34.value,'dlarray') && any(dims(Int_34.value) == 'U'))
                Int_34 = permute(Int_34.value, fliplr(1:max(2,Int_34.rank)));
            else
                Int_34 = dlarray(single(Int_34.value), 'UU');
            end

        end



        function [CallMethod_54, Int_27, Int_46, Int_24, Int_43, Int_21, Int_40, Int_18, Int_37, Int_15, Int_34, CallMethod_54_rank, Int_27_rank, Int_46_rank, Int_24_rank, Int_43_rank, Int_21_rank, Int_40_rank, Int_18_rank, Int_37_rank, Int_15_rank, Int_34_rank] = forward(obj,CallMethod_argument1_1)

            %Use the input format inferred by the importer to permute the input into reverse-PyTorch dimension order
            [CallMethod_argument1_1, CallMethod_argument1_1_format] = segformer_eager.ops.permuteToReversePyTorch(CallMethod_argument1_1, '*CSS', '');

            if ~contains(CallMethod_argument1_1_format,'U')
                [CallMethod_argument1_1] = struct('value', CallMethod_argument1_1, 'rank', numel(CallMethod_argument1_1_format));
            end

            [CallMethod_54, Int_27, Int_46, Int_24, Int_43, Int_21, Int_40, Int_18, Int_37, Int_15, Int_34] = tracedPyTorchFunction(obj,CallMethod_argument1_1,true,"forward");

            [CallMethod_54_rank] = ones([1,CallMethod_54.rank], 'single');
            CallMethod_54_rank = dlarray(CallMethod_54_rank,'UU');
            %Permute U-labelled output to forward PyTorch dimension ordering
            if(isa(CallMethod_54.value,'dlarray') && any(dims(CallMethod_54.value) == 'U'))
                CallMethod_54 = permute(CallMethod_54.value, fliplr(1:max(2,CallMethod_54.rank)));
            else
                CallMethod_54 = dlarray(single(CallMethod_54.value), 'UU');
            end
            [Int_27_rank] = ones([1,Int_27.rank], 'single');
            Int_27_rank = dlarray(Int_27_rank,'UU');
            %Permute U-labelled output to forward PyTorch dimension ordering
            if(isa(Int_27.value,'dlarray') && any(dims(Int_27.value) == 'U'))
                Int_27 = permute(Int_27.value, fliplr(1:max(2,Int_27.rank)));
            else
                Int_27 = dlarray(single(Int_27.value), 'UU');
            end
            [Int_46_rank] = ones([1,Int_46.rank], 'single');
            Int_46_rank = dlarray(Int_46_rank,'UU');
            %Permute U-labelled output to forward PyTorch dimension ordering
            if(isa(Int_46.value,'dlarray') && any(dims(Int_46.value) == 'U'))
                Int_46 = permute(Int_46.value, fliplr(1:max(2,Int_46.rank)));
            else
                Int_46 = dlarray(single(Int_46.value), 'UU');
            end
            [Int_24_rank] = ones([1,Int_24.rank], 'single');
            Int_24_rank = dlarray(Int_24_rank,'UU');
            %Permute U-labelled output to forward PyTorch dimension ordering
            if(isa(Int_24.value,'dlarray') && any(dims(Int_24.value) == 'U'))
                Int_24 = permute(Int_24.value, fliplr(1:max(2,Int_24.rank)));
            else
                Int_24 = dlarray(single(Int_24.value), 'UU');
            end
            [Int_43_rank] = ones([1,Int_43.rank], 'single');
            Int_43_rank = dlarray(Int_43_rank,'UU');
            %Permute U-labelled output to forward PyTorch dimension ordering
            if(isa(Int_43.value,'dlarray') && any(dims(Int_43.value) == 'U'))
                Int_43 = permute(Int_43.value, fliplr(1:max(2,Int_43.rank)));
            else
                Int_43 = dlarray(single(Int_43.value), 'UU');
            end
            [Int_21_rank] = ones([1,Int_21.rank], 'single');
            Int_21_rank = dlarray(Int_21_rank,'UU');
            %Permute U-labelled output to forward PyTorch dimension ordering
            if(isa(Int_21.value,'dlarray') && any(dims(Int_21.value) == 'U'))
                Int_21 = permute(Int_21.value, fliplr(1:max(2,Int_21.rank)));
            else
                Int_21 = dlarray(single(Int_21.value), 'UU');
            end
            [Int_40_rank] = ones([1,Int_40.rank], 'single');
            Int_40_rank = dlarray(Int_40_rank,'UU');
            %Permute U-labelled output to forward PyTorch dimension ordering
            if(isa(Int_40.value,'dlarray') && any(dims(Int_40.value) == 'U'))
                Int_40 = permute(Int_40.value, fliplr(1:max(2,Int_40.rank)));
            else
                Int_40 = dlarray(single(Int_40.value), 'UU');
            end
            [Int_18_rank] = ones([1,Int_18.rank], 'single');
            Int_18_rank = dlarray(Int_18_rank,'UU');
            %Permute U-labelled output to forward PyTorch dimension ordering
            if(isa(Int_18.value,'dlarray') && any(dims(Int_18.value) == 'U'))
                Int_18 = permute(Int_18.value, fliplr(1:max(2,Int_18.rank)));
            else
                Int_18 = dlarray(single(Int_18.value), 'UU');
            end
            [Int_37_rank] = ones([1,Int_37.rank], 'single');
            Int_37_rank = dlarray(Int_37_rank,'UU');
            %Permute U-labelled output to forward PyTorch dimension ordering
            if(isa(Int_37.value,'dlarray') && any(dims(Int_37.value) == 'U'))
                Int_37 = permute(Int_37.value, fliplr(1:max(2,Int_37.rank)));
            else
                Int_37 = dlarray(single(Int_37.value), 'UU');
            end
            [Int_15_rank] = ones([1,Int_15.rank], 'single');
            Int_15_rank = dlarray(Int_15_rank,'UU');
            %Permute U-labelled output to forward PyTorch dimension ordering
            if(isa(Int_15.value,'dlarray') && any(dims(Int_15.value) == 'U'))
                Int_15 = permute(Int_15.value, fliplr(1:max(2,Int_15.rank)));
            else
                Int_15 = dlarray(single(Int_15.value), 'UU');
            end
            [Int_34_rank] = ones([1,Int_34.rank], 'single');
            Int_34_rank = dlarray(Int_34_rank,'UU');
            %Permute U-labelled output to forward PyTorch dimension ordering
            if(isa(Int_34.value,'dlarray') && any(dims(Int_34.value) == 'U'))
                Int_34 = permute(Int_34.value, fliplr(1:max(2,Int_34.rank)));
            else
                Int_34 = dlarray(single(Int_34.value), 'UU');
            end

        end



        function [CallMethod_54, Int_27, Int_46, Int_24, Int_43, Int_21, Int_40, Int_18, Int_37, Int_15, Int_34] = tracedPyTorchFunction(obj,CallMethod_argument1_1,isForward,predict)

            [Constant_48] = segformer_eager.ops.makeStructForConstant(int64(obj.Constant_48), int64(0), "Typed");
            [Constant_10] = segformer_eager.ops.makeStructForConstant(int64(obj.Constant_10), int64(0), "Typed");
            [Constant_29] = segformer_eager.ops.makeStructForConstant(int64(obj.Constant_29), int64(0), "Typed");
            [Constant_50] = segformer_eager.ops.makeStructForConstant(int64(obj.Constant_50), int64(0), "Typed");
            GetAttr_layernorm_1 = obj.Param_layer_norm;


            GetAttr_proj_1 = obj.Param_proj;

            GetAttr_proj_1_InputFormat1 = '*CSS';


            [CallMethod_argument1_1_labelled] = segformer_eager.ops.labelWithPropagatedFormats(CallMethod_argument1_1, GetAttr_proj_1_InputFormat1);
            [CallMethod_8] = GetAttr_proj_1.(predict)(CallMethod_argument1_1_labelled.value);
            [CallMethod_8, CallMethod_8_format] = segformer_eager.ops.permuteToReversePyTorch(CallMethod_8, '*CSS', '');
            if ~contains(CallMethod_8_format,'U')
                [CallMethod_8] = struct('value', CallMethod_8, 'rank', numel(CallMethod_8_format));
            else
                [CallMethod_8] = struct('value', CallMethod_8, 'rank', '');
            end

            [size_11] = segformer_eager.ops.pySize(CallMethod_8, Constant_10);
            [NumToTensor_height_1] = segformer_eager.ops.makeStructForConstant(single(size_11.value), int64([size_11.rank]), "Tensor");
            [Int_15] = segformer_eager.ops.makeStructForConstant(NumToTensor_height_1.value, int64([NumToTensor_height_1.rank]), "Integer");
            [Int_18] = segformer_eager.ops.makeStructForConstant(NumToTensor_height_1.value, int64([NumToTensor_height_1.rank]), "Integer");
            [Int_21] = segformer_eager.ops.makeStructForConstant(NumToTensor_height_1.value, int64([NumToTensor_height_1.rank]), "Integer");
            [Int_24] = segformer_eager.ops.makeStructForConstant(NumToTensor_height_1.value, int64([NumToTensor_height_1.rank]), "Integer");
            [Int_27] = segformer_eager.ops.makeStructForConstant(NumToTensor_height_1.value, int64([NumToTensor_height_1.rank]), "Integer");
            [size_30] = segformer_eager.ops.pySize(CallMethod_8, Constant_29);
            [NumToTensor_width_1] = segformer_eager.ops.makeStructForConstant(single(size_30.value), int64([size_30.rank]), "Tensor");
            [Int_34] = segformer_eager.ops.makeStructForConstant(NumToTensor_width_1.value, int64([NumToTensor_width_1.rank]), "Integer");
            [Int_37] = segformer_eager.ops.makeStructForConstant(NumToTensor_width_1.value, int64([NumToTensor_width_1.rank]), "Integer");
            [Int_40] = segformer_eager.ops.makeStructForConstant(NumToTensor_width_1.value, int64([NumToTensor_width_1.rank]), "Integer");
            [Int_43] = segformer_eager.ops.makeStructForConstant(NumToTensor_width_1.value, int64([NumToTensor_width_1.rank]), "Integer");
            [Int_46] = segformer_eager.ops.makeStructForConstant(NumToTensor_width_1.value, int64([NumToTensor_width_1.rank]), "Integer");
            [flatten_49] = segformer_eager.ops.pyFlatten(CallMethod_8, Constant_10, Constant_48);
            [transpose_input_1] = segformer_eager.ops.pyTranspose(flatten_49, Constant_50, Constant_10);

            transpose_input_1_labelled = transpose_input_1;
            transpose_input_1_labelled.value = permute(transpose_input_1_labelled.value, fliplr(1:max(2,transpose_input_1_labelled.rank)));
            [CallMethod_54,CallMethod_54_rank] = GetAttr_layernorm_1.(predict)(transpose_input_1_labelled.value,dlarray(ones(1,transpose_input_1.rank),'UU'));
            [CallMethod_54, CallMethod_54_format] = segformer_eager.ops.permuteToReversePyTorch(CallMethod_54, '', int64(numel(CallMethod_54_rank)));
            if ~contains(CallMethod_54_format,'U')
                [CallMethod_54] = struct('value', CallMethod_54, 'rank', numel(CallMethod_54_format));
            else
                [CallMethod_54] = struct('value', CallMethod_54, 'rank', int64(max([2, ndims(CallMethod_54), numel(CallMethod_54_rank)])));
            end

        end

    end
end

