classdef modelingsegformer_torchmangle125_SegformerOverlapPatchEmbeddings < nnet.layer.Layer & nnet.layer.Formattable & ...
        nnet.layer.AutogeneratedFromPyTorch & nnet.layer.Acceleratable
    %modelingsegformer_torchmangle125_SegformerOverlapPatchEmbeddings Auto-generated custom layer
    % Auto-generated by MATLAB on 04-Sep-2026 18:43:53

    properties (Learnable)
        % Networks (type dlnetwork)

        Param_proj
        Param_layer_norm
    end

    properties
        % Non-Trainable Parameters
        Constant_36
        Constant_10
        Constant_23
        Constant_38



    end

    properties (Learnable)
        % Trainable Parameters

    end

    methods
        function obj = modelingsegformer_torchmangle125_SegformerOverlapPatchEmbeddings(Name, Type, InputNames, OutputNames)
            obj.Name = Name;
            obj.Type = Type;
            obj.NumInputs = 1;
            obj.NumOutputs = 14;
            obj.InputNames = InputNames;
            obj.OutputNames = OutputNames;
        end

        function [CallMethod_42, Int_21, Int_34, Int_18, Int_31, Int_15, Int_28, CallMethod_42_rank, Int_21_rank, Int_34_rank, Int_18_rank, Int_31_rank, Int_15_rank, Int_28_rank] = predict(obj,CallMethod_argument1_1)

            %Use the input format inferred by the importer to permute the input into reverse-PyTorch dimension order
            [CallMethod_argument1_1, CallMethod_argument1_1_format] = segformer_eager.ops.permuteToReversePyTorch(CallMethod_argument1_1, '*CSS', '');

            if ~contains(CallMethod_argument1_1_format,'U')
                [CallMethod_argument1_1] = struct('value', CallMethod_argument1_1, 'rank', numel(CallMethod_argument1_1_format));
            end

            [CallMethod_42, Int_21, Int_34, Int_18, Int_31, Int_15, Int_28] = tracedPyTorchFunction(obj,CallMethod_argument1_1,false,"predict");

            [CallMethod_42_rank] = ones([1,CallMethod_42.rank], 'single');
            CallMethod_42_rank = dlarray(CallMethod_42_rank,'UU');
            %Permute U-labelled output to forward PyTorch dimension ordering
            if(isa(CallMethod_42.value,'dlarray') && any(dims(CallMethod_42.value) == 'U'))
                CallMethod_42 = permute(CallMethod_42.value, fliplr(1:max(2,CallMethod_42.rank)));
            else
                CallMethod_42 = dlarray(single(CallMethod_42.value), 'UU');
            end
            [Int_21_rank] = ones([1,Int_21.rank], 'single');
            Int_21_rank = dlarray(Int_21_rank,'UU');
            %Permute U-labelled output to forward PyTorch dimension ordering
            if(isa(Int_21.value,'dlarray') && any(dims(Int_21.value) == 'U'))
                Int_21 = permute(Int_21.value, fliplr(1:max(2,Int_21.rank)));
            else
                Int_21 = dlarray(single(Int_21.value), 'UU');
            end
            [Int_34_rank] = ones([1,Int_34.rank], 'single');
            Int_34_rank = dlarray(Int_34_rank,'UU');
            %Permute U-labelled output to forward PyTorch dimension ordering
            if(isa(Int_34.value,'dlarray') && any(dims(Int_34.value) == 'U'))
                Int_34 = permute(Int_34.value, fliplr(1:max(2,Int_34.rank)));
            else
                Int_34 = dlarray(single(Int_34.value), 'UU');
            end
            [Int_18_rank] = ones([1,Int_18.rank], 'single');
            Int_18_rank = dlarray(Int_18_rank,'UU');
            %Permute U-labelled output to forward PyTorch dimension ordering
            if(isa(Int_18.value,'dlarray') && any(dims(Int_18.value) == 'U'))
                Int_18 = permute(Int_18.value, fliplr(1:max(2,Int_18.rank)));
            else
                Int_18 = dlarray(single(Int_18.value), 'UU');
            end
            [Int_31_rank] = ones([1,Int_31.rank], 'single');
            Int_31_rank = dlarray(Int_31_rank,'UU');
            %Permute U-labelled output to forward PyTorch dimension ordering
            if(isa(Int_31.value,'dlarray') && any(dims(Int_31.value) == 'U'))
                Int_31 = permute(Int_31.value, fliplr(1:max(2,Int_31.rank)));
            else
                Int_31 = dlarray(single(Int_31.value), 'UU');
            end
            [Int_15_rank] = ones([1,Int_15.rank], 'single');
            Int_15_rank = dlarray(Int_15_rank,'UU');
            %Permute U-labelled output to forward PyTorch dimension ordering
            if(isa(Int_15.value,'dlarray') && any(dims(Int_15.value) == 'U'))
                Int_15 = permute(Int_15.value, fliplr(1:max(2,Int_15.rank)));
            else
                Int_15 = dlarray(single(Int_15.value), 'UU');
            end
            [Int_28_rank] = ones([1,Int_28.rank], 'single');
            Int_28_rank = dlarray(Int_28_rank,'UU');
            %Permute U-labelled output to forward PyTorch dimension ordering
            if(isa(Int_28.value,'dlarray') && any(dims(Int_28.value) == 'U'))
                Int_28 = permute(Int_28.value, fliplr(1:max(2,Int_28.rank)));
            else
                Int_28 = dlarray(single(Int_28.value), 'UU');
            end

        end



        function [CallMethod_42, Int_21, Int_34, Int_18, Int_31, Int_15, Int_28, CallMethod_42_rank, Int_21_rank, Int_34_rank, Int_18_rank, Int_31_rank, Int_15_rank, Int_28_rank] = forward(obj,CallMethod_argument1_1)

            %Use the input format inferred by the importer to permute the input into reverse-PyTorch dimension order
            [CallMethod_argument1_1, CallMethod_argument1_1_format] = segformer_eager.ops.permuteToReversePyTorch(CallMethod_argument1_1, '*CSS', '');

            if ~contains(CallMethod_argument1_1_format,'U')
                [CallMethod_argument1_1] = struct('value', CallMethod_argument1_1, 'rank', numel(CallMethod_argument1_1_format));
            end

            [CallMethod_42, Int_21, Int_34, Int_18, Int_31, Int_15, Int_28] = tracedPyTorchFunction(obj,CallMethod_argument1_1,true,"forward");

            [CallMethod_42_rank] = ones([1,CallMethod_42.rank], 'single');
            CallMethod_42_rank = dlarray(CallMethod_42_rank,'UU');
            %Permute U-labelled output to forward PyTorch dimension ordering
            if(isa(CallMethod_42.value,'dlarray') && any(dims(CallMethod_42.value) == 'U'))
                CallMethod_42 = permute(CallMethod_42.value, fliplr(1:max(2,CallMethod_42.rank)));
            else
                CallMethod_42 = dlarray(single(CallMethod_42.value), 'UU');
            end
            [Int_21_rank] = ones([1,Int_21.rank], 'single');
            Int_21_rank = dlarray(Int_21_rank,'UU');
            %Permute U-labelled output to forward PyTorch dimension ordering
            if(isa(Int_21.value,'dlarray') && any(dims(Int_21.value) == 'U'))
                Int_21 = permute(Int_21.value, fliplr(1:max(2,Int_21.rank)));
            else
                Int_21 = dlarray(single(Int_21.value), 'UU');
            end
            [Int_34_rank] = ones([1,Int_34.rank], 'single');
            Int_34_rank = dlarray(Int_34_rank,'UU');
            %Permute U-labelled output to forward PyTorch dimension ordering
            if(isa(Int_34.value,'dlarray') && any(dims(Int_34.value) == 'U'))
                Int_34 = permute(Int_34.value, fliplr(1:max(2,Int_34.rank)));
            else
                Int_34 = dlarray(single(Int_34.value), 'UU');
            end
            [Int_18_rank] = ones([1,Int_18.rank], 'single');
            Int_18_rank = dlarray(Int_18_rank,'UU');
            %Permute U-labelled output to forward PyTorch dimension ordering
            if(isa(Int_18.value,'dlarray') && any(dims(Int_18.value) == 'U'))
                Int_18 = permute(Int_18.value, fliplr(1:max(2,Int_18.rank)));
            else
                Int_18 = dlarray(single(Int_18.value), 'UU');
            end
            [Int_31_rank] = ones([1,Int_31.rank], 'single');
            Int_31_rank = dlarray(Int_31_rank,'UU');
            %Permute U-labelled output to forward PyTorch dimension ordering
            if(isa(Int_31.value,'dlarray') && any(dims(Int_31.value) == 'U'))
                Int_31 = permute(Int_31.value, fliplr(1:max(2,Int_31.rank)));
            else
                Int_31 = dlarray(single(Int_31.value), 'UU');
            end
            [Int_15_rank] = ones([1,Int_15.rank], 'single');
            Int_15_rank = dlarray(Int_15_rank,'UU');
            %Permute U-labelled output to forward PyTorch dimension ordering
            if(isa(Int_15.value,'dlarray') && any(dims(Int_15.value) == 'U'))
                Int_15 = permute(Int_15.value, fliplr(1:max(2,Int_15.rank)));
            else
                Int_15 = dlarray(single(Int_15.value), 'UU');
            end
            [Int_28_rank] = ones([1,Int_28.rank], 'single');
            Int_28_rank = dlarray(Int_28_rank,'UU');
            %Permute U-labelled output to forward PyTorch dimension ordering
            if(isa(Int_28.value,'dlarray') && any(dims(Int_28.value) == 'U'))
                Int_28 = permute(Int_28.value, fliplr(1:max(2,Int_28.rank)));
            else
                Int_28 = dlarray(single(Int_28.value), 'UU');
            end

        end



        function [CallMethod_42, Int_21, Int_34, Int_18, Int_31, Int_15, Int_28] = tracedPyTorchFunction(obj,CallMethod_argument1_1,isForward,predict)

            [Constant_36] = segformer_eager.ops.makeStructForConstant(int64(obj.Constant_36), int64(0), "Typed");
            [Constant_10] = segformer_eager.ops.makeStructForConstant(int64(obj.Constant_10), int64(0), "Typed");
            [Constant_23] = segformer_eager.ops.makeStructForConstant(int64(obj.Constant_23), int64(0), "Typed");
            [Constant_38] = segformer_eager.ops.makeStructForConstant(int64(obj.Constant_38), int64(0), "Typed");
            GetAttr_layernorm_1 = obj.Param_layer_norm;


            GetAttr_proj_1 = obj.Param_proj;

            GetAttr_proj_1_InputFormat1 = '*CSS';


            [CallMethod_argument1_1_labelled] = segformer_eager.ops.labelWithPropagatedFormats(CallMethod_argument1_1, GetAttr_proj_1_InputFormat1);
            [CallMethod_8] = GetAttr_proj_1.(predict)(CallMethod_argument1_1_labelled.value);
            [CallMethod_8, CallMethod_8_format] = segformer_eager.ops.permuteToReversePyTorch(CallMethod_8, '*CSS', '');
            if ~contains(CallMethod_8_format,'U')
                [CallMethod_8] = struct('value', CallMethod_8, 'rank', numel(CallMethod_8_format));
            else
                [CallMethod_8] = struct('value', CallMethod_8, 'rank', '');
            end

            [size_11] = segformer_eager.ops.pySize(CallMethod_8, Constant_10);
            [NumToTensor_height_1] = segformer_eager.ops.makeStructForConstant(single(size_11.value), int64([size_11.rank]), "Tensor");
            [Int_15] = segformer_eager.ops.makeStructForConstant(NumToTensor_height_1.value, int64([NumToTensor_height_1.rank]), "Integer");
            [Int_18] = segformer_eager.ops.makeStructForConstant(NumToTensor_height_1.value, int64([NumToTensor_height_1.rank]), "Integer");
            [Int_21] = segformer_eager.ops.makeStructForConstant(NumToTensor_height_1.value, int64([NumToTensor_height_1.rank]), "Integer");
            [size_24] = segformer_eager.ops.pySize(CallMethod_8, Constant_23);
            [NumToTensor_width_1] = segformer_eager.ops.makeStructForConstant(single(size_24.value), int64([size_24.rank]), "Tensor");
            [Int_28] = segformer_eager.ops.makeStructForConstant(NumToTensor_width_1.value, int64([NumToTensor_width_1.rank]), "Integer");
            [Int_31] = segformer_eager.ops.makeStructForConstant(NumToTensor_width_1.value, int64([NumToTensor_width_1.rank]), "Integer");
            [Int_34] = segformer_eager.ops.makeStructForConstant(NumToTensor_width_1.value, int64([NumToTensor_width_1.rank]), "Integer");
            [flatten_37] = segformer_eager.ops.pyFlatten(CallMethod_8, Constant_10, Constant_36);
            [transpose_input_1] = segformer_eager.ops.pyTranspose(flatten_37, Constant_38, Constant_10);

            transpose_input_1_labelled = transpose_input_1;
            transpose_input_1_labelled.value = permute(transpose_input_1_labelled.value, fliplr(1:max(2,transpose_input_1_labelled.rank)));
            [CallMethod_42,CallMethod_42_rank] = GetAttr_layernorm_1.(predict)(transpose_input_1_labelled.value,dlarray(ones(1,transpose_input_1.rank),'UU'));
            [CallMethod_42, CallMethod_42_format] = segformer_eager.ops.permuteToReversePyTorch(CallMethod_42, '', int64(numel(CallMethod_42_rank)));
            if ~contains(CallMethod_42_format,'U')
                [CallMethod_42] = struct('value', CallMethod_42, 'rank', numel(CallMethod_42_format));
            else
                [CallMethod_42] = struct('value', CallMethod_42, 'rank', int64(max([2, ndims(CallMethod_42), numel(CallMethod_42_rank)])));
            end

        end

    end
end

