classdef segformer_modelingsegformer_SegformerDecodeHead < nnet.layer.Layer & nnet.layer.Formattable & ...
        nnet.layer.AutogeneratedFromPyTorch & nnet.layer.Acceleratable
    %segformer_modelingsegformer_SegformerDecodeHead Auto-generated custom layer
    % Auto-generated by MATLAB on 04-Sep-2026 18:44:01

    properties (Learnable)
        % Networks (type dlnetwork)

        Param_linear_projections_0
        Param_linear_projections_1
        Param_linear_projections_2
        Param_linear_projections_3
        Param_linear_fuse
        Param_batch_norm
        Param_activation
        Param_dropout
        Param_classifier
    end

    properties
        % Non-Trainable Parameters
        Constant_89
        Constant_88
        Constant_32
        Constant_48
        Constant_55
        Constant_64
        Constant_68



    end

    properties (Learnable)
        % Trainable Parameters

    end

    methods
        function obj = segformer_modelingsegformer_SegformerDecodeHead(Name, Type, InputNames, OutputNames)
            obj.Name = Name;
            obj.Type = Type;
            obj.NumInputs = 5;
            obj.NumOutputs = 1;
            obj.InputNames = InputNames;
            obj.OutputNames = OutputNames;
        end

        function [CallMethod_230] = predict(obj,size_argument1_1, size_argument2_1, size_argument3_1, size_argument4_1, size_argument1_1_rank)

            %Use the input format inferred by the importer to permute the input into reverse-PyTorch dimension order
            [size_argument1_1, size_argument1_1_format] = segformer_eager.ops.permuteToReversePyTorch(size_argument1_1, '', numel(size_argument1_1_rank));

            %Use the input format inferred by the importer to permute the input into reverse-PyTorch dimension order
            [size_argument2_1, size_argument2_1_format] = segformer_eager.ops.permuteToReversePyTorch(size_argument2_1, '*CSS', '');

            %Use the input format inferred by the importer to permute the input into reverse-PyTorch dimension order
            [size_argument3_1, size_argument3_1_format] = segformer_eager.ops.permuteToReversePyTorch(size_argument3_1, '*CSS', '');

            %Use the input format inferred by the importer to permute the input into reverse-PyTorch dimension order
            [size_argument4_1, size_argument4_1_format] = segformer_eager.ops.permuteToReversePyTorch(size_argument4_1, '*CSS', '');
            [size_argument1_1] = struct('value', size_argument1_1, 'rank', int64(max([2, ndims(size_argument1_1), numel(size_argument1_1_rank)])));

            if ~contains(size_argument2_1_format,'U')
                [size_argument2_1] = struct('value', size_argument2_1, 'rank', numel(size_argument2_1_format));
            end

            if ~contains(size_argument3_1_format,'U')
                [size_argument3_1] = struct('value', size_argument3_1, 'rank', numel(size_argument3_1_format));
            end

            if ~contains(size_argument4_1_format,'U')
                [size_argument4_1] = struct('value', size_argument4_1, 'rank', numel(size_argument4_1_format));
            end

            [CallMethod_230] = tracedPyTorchFunction(obj,size_argument1_1, size_argument2_1, size_argument3_1, size_argument4_1,false,"predict");


            [CallMethod_230] = segformer_eager.ops.labelWithPropagatedFormats(CallMethod_230, "BCSS");
            CallMethod_230 = CallMethod_230.value ;

        end



        function [CallMethod_230] = forward(obj,size_argument1_1, size_argument2_1, size_argument3_1, size_argument4_1, size_argument1_1_rank)

            %Use the input format inferred by the importer to permute the input into reverse-PyTorch dimension order
            [size_argument1_1, size_argument1_1_format] = segformer_eager.ops.permuteToReversePyTorch(size_argument1_1, '', numel(size_argument1_1_rank));

            %Use the input format inferred by the importer to permute the input into reverse-PyTorch dimension order
            [size_argument2_1, size_argument2_1_format] = segformer_eager.ops.permuteToReversePyTorch(size_argument2_1, '*CSS', '');

            %Use the input format inferred by the importer to permute the input into reverse-PyTorch dimension order
            [size_argument3_1, size_argument3_1_format] = segformer_eager.ops.permuteToReversePyTorch(size_argument3_1, '*CSS', '');

            %Use the input format inferred by the importer to permute the input into reverse-PyTorch dimension order
            [size_argument4_1, size_argument4_1_format] = segformer_eager.ops.permuteToReversePyTorch(size_argument4_1, '*CSS', '');
            [size_argument1_1] = struct('value', size_argument1_1, 'rank', int64(max([2, ndims(size_argument1_1), numel(size_argument1_1_rank)])));

            if ~contains(size_argument2_1_format,'U')
                [size_argument2_1] = struct('value', size_argument2_1, 'rank', numel(size_argument2_1_format));
            end

            if ~contains(size_argument3_1_format,'U')
                [size_argument3_1] = struct('value', size_argument3_1, 'rank', numel(size_argument3_1_format));
            end

            if ~contains(size_argument4_1_format,'U')
                [size_argument4_1] = struct('value', size_argument4_1, 'rank', numel(size_argument4_1_format));
            end

            [CallMethod_230] = tracedPyTorchFunction(obj,size_argument1_1, size_argument2_1, size_argument3_1, size_argument4_1,true,"forward");


            [CallMethod_230] = segformer_eager.ops.labelWithPropagatedFormats(CallMethod_230, "BCSS");
            CallMethod_230 = CallMethod_230.value ;

        end



        function [CallMethod_230] = tracedPyTorchFunction(obj,size_argument1_1, size_argument2_1, size_argument3_1, size_argument4_1,isForward,predict)

            [Constant_89] = segformer_eager.ops.makeStructForConstant(double(obj.Constant_89), int64(0), "Typed");
            [Constant_88] = segformer_eager.ops.makeStructForConstant(int64(obj.Constant_88), int64(0), "Typed");
            [Constant_32] = segformer_eager.ops.makeStructForConstant(int64(obj.Constant_32), int64(0), "Typed");
            [Constant_48] = segformer_eager.ops.makeStructForConstant(int64(obj.Constant_48), int64(0), "Typed");
            [Constant_55] = segformer_eager.ops.makeStructForConstant(int64(obj.Constant_55), int64(0), "Typed");
            [Constant_64] = segformer_eager.ops.makeStructForConstant(int64(obj.Constant_64), int64(0), "Typed");
            [Constant_68] = segformer_eager.ops.makeStructForConstant(int64(obj.Constant_68), int64(0), "Typed");
            GetAttr_classifier_1 = obj.Param_classifier;

            GetAttr_classifier_1_InputFormat1 = 'BCSS';

            GetAttr_dropout_1 = obj.Param_dropout;

            GetAttr_dropout_1_InputFormat1 = 'BCSS';

            GetAttr_activation_1 = obj.Param_activation;

            GetAttr_activation_1_InputFormat1 = 'BCSS';

            GetAttr_batchnorm_1 = obj.Param_batch_norm;

            GetAttr_batchnorm_1_InputFormat1 = 'BCSS';

            GetAttr_linearfuse_1 = obj.Param_linear_fuse;

            GetAttr_linearfuse_1_InputFormat1 = 'BCSS';

            GetAttr_3 = obj.Param_linear_projections_3;


            GetAttr_2 = obj.Param_linear_projections_2;

            GetAttr_2_InputFormat1 = '*CSS';

            GetAttr_1 = obj.Param_linear_projections_1;

            GetAttr_1_InputFormat1 = '*CSS';

            GetAttr_0 = obj.Param_linear_projections_0;

            GetAttr_0_InputFormat1 = '*CSS';

            [size_33] = segformer_eager.ops.pySize(size_argument1_1, Constant_32);
            [NumToTensor_batchsize_1] = segformer_eager.ops.makeStructForConstant(single(size_33.value), int64([size_33.rank]), "Tensor");
            [Int_37] = segformer_eager.ops.makeStructForConstant(NumToTensor_batchsize_1.value, int64([NumToTensor_batchsize_1.rank]), "Integer");
            [Int_40] = segformer_eager.ops.makeStructForConstant(NumToTensor_batchsize_1.value, int64([NumToTensor_batchsize_1.rank]), "Integer");
            [Int_43] = segformer_eager.ops.makeStructForConstant(NumToTensor_batchsize_1.value, int64([NumToTensor_batchsize_1.rank]), "Integer");
            [Int_46] = segformer_eager.ops.makeStructForConstant(NumToTensor_batchsize_1.value, int64([NumToTensor_batchsize_1.rank]), "Integer");
            [size_49] = segformer_eager.ops.pySize(size_argument2_1, Constant_48);
            [NumToTensor_height_1] = segformer_eager.ops.makeStructForConstant(single(size_49.value), int64([size_49.rank]), "Tensor");
            [Int_53] = segformer_eager.ops.makeStructForConstant(NumToTensor_height_1.value, int64([NumToTensor_height_1.rank]), "Integer");
            [size_56] = segformer_eager.ops.pySize(size_argument2_1, Constant_55);
            [NumToTensor_width_1] = segformer_eager.ops.makeStructForConstant(single(size_56.value), int64([size_56.rank]), "Tensor");
            [Int_60] = segformer_eager.ops.makeStructForConstant(NumToTensor_width_1.value, int64([NumToTensor_width_1.rank]), "Integer");

            [size_argument2_1_labelled] = segformer_eager.ops.labelWithPropagatedFormats(size_argument2_1, GetAttr_0_InputFormat1);
            [CallMethod_63,CallMethod_63_rank] = GetAttr_0.(predict)(size_argument2_1_labelled.value);
            [CallMethod_63, CallMethod_63_format] = segformer_eager.ops.permuteToReversePyTorch(CallMethod_63, '', int64(numel(CallMethod_63_rank)));
            if ~contains(CallMethod_63_format,'U')
                [CallMethod_63] = struct('value', CallMethod_63, 'rank', numel(CallMethod_63_format));
            else
                [CallMethod_63] = struct('value', CallMethod_63, 'rank', int64(max([2, ndims(CallMethod_63), numel(CallMethod_63_rank)])));
            end

            [transpose_encoderhiddenstate_1] = segformer_eager.ops.pyTranspose(CallMethod_63, Constant_64, Constant_48);
            [ListConstruct_71] = segformer_eager.ops.pyListConstruct(Int_46, Constant_68, Int_53, Int_60);
            [reshape_input_1] = segformer_eager.ops.pyView(transpose_encoderhiddenstate_1, ListConstruct_71);
            [size_74] = segformer_eager.ops.pySize(size_argument2_1, Constant_48);
            [NumToTensor_75] = segformer_eager.ops.makeStructForConstant(single(size_74.value), int64([size_74.rank]), "Tensor");
            [Int_78] = segformer_eager.ops.makeStructForConstant(NumToTensor_75.value, int64([NumToTensor_75.rank]), "Integer");
            [size_80] = segformer_eager.ops.pySize(size_argument2_1, Constant_55);
            [NumToTensor_81] = segformer_eager.ops.makeStructForConstant(single(size_80.value), int64([size_80.rank]), "Tensor");
            [Int_86] = segformer_eager.ops.makeStructForConstant(NumToTensor_81.value, int64([NumToTensor_81.rank]), "Integer");
            [ListConstruct_87] = segformer_eager.ops.pyListConstruct(Int_78, Int_86);
            [upsamplebilinear2d_90] = segformer_eager.ops.pyUpsample2d(reshape_input_1, 'linear', ListConstruct_87, Constant_88, Constant_89);
            [size_92] = segformer_eager.ops.pySize(size_argument3_1, Constant_48);
            [NumToTensor_height0_1] = segformer_eager.ops.makeStructForConstant(single(size_92.value), int64([size_92.rank]), "Tensor");
            [Int_96] = segformer_eager.ops.makeStructForConstant(NumToTensor_height0_1.value, int64([NumToTensor_height0_1.rank]), "Integer");
            [size_98] = segformer_eager.ops.pySize(size_argument3_1, Constant_55);
            [NumToTensor_width0_1] = segformer_eager.ops.makeStructForConstant(single(size_98.value), int64([size_98.rank]), "Tensor");
            [Int_102] = segformer_eager.ops.makeStructForConstant(NumToTensor_width0_1.value, int64([NumToTensor_width0_1.rank]), "Integer");

            [size_argument3_1_labelled] = segformer_eager.ops.labelWithPropagatedFormats(size_argument3_1, GetAttr_1_InputFormat1);
            [CallMethod_105,CallMethod_105_rank] = GetAttr_1.(predict)(size_argument3_1_labelled.value);
            [CallMethod_105, CallMethod_105_format] = segformer_eager.ops.permuteToReversePyTorch(CallMethod_105, '', int64(numel(CallMethod_105_rank)));
            if ~contains(CallMethod_105_format,'U')
                [CallMethod_105] = struct('value', CallMethod_105, 'rank', numel(CallMethod_105_format));
            else
                [CallMethod_105] = struct('value', CallMethod_105, 'rank', int64(max([2, ndims(CallMethod_105), numel(CallMethod_105_rank)])));
            end

            [transpose_encoderhiddenstate0_1] = segformer_eager.ops.pyTranspose(CallMethod_105, Constant_64, Constant_48);
            [ListConstruct_111] = segformer_eager.ops.pyListConstruct(Int_43, Constant_68, Int_96, Int_102);
            [reshape_input3_1] = segformer_eager.ops.pyView(transpose_encoderhiddenstate0_1, ListConstruct_111);
            [size_114] = segformer_eager.ops.pySize(size_argument2_1, Constant_48);
            [NumToTensor_115] = segformer_eager.ops.makeStructForConstant(single(size_114.value), int64([size_114.rank]), "Tensor");
            [Int_118] = segformer_eager.ops.makeStructForConstant(NumToTensor_115.value, int64([NumToTensor_115.rank]), "Integer");
            [size_120] = segformer_eager.ops.pySize(size_argument2_1, Constant_55);
            [NumToTensor_121] = segformer_eager.ops.makeStructForConstant(single(size_120.value), int64([size_120.rank]), "Tensor");
            [Int_126] = segformer_eager.ops.makeStructForConstant(NumToTensor_121.value, int64([NumToTensor_121.rank]), "Integer");
            [ListConstruct_127] = segformer_eager.ops.pyListConstruct(Int_118, Int_126);
            [upsamplebilinear2d_130] = segformer_eager.ops.pyUpsample2d(reshape_input3_1, 'linear', ListConstruct_127, Constant_88, Constant_89);
            [size_132] = segformer_eager.ops.pySize(size_argument4_1, Constant_48);
            [NumToTensor_height1_1] = segformer_eager.ops.makeStructForConstant(single(size_132.value), int64([size_132.rank]), "Tensor");
            [Int_136] = segformer_eager.ops.makeStructForConstant(NumToTensor_height1_1.value, int64([NumToTensor_height1_1.rank]), "Integer");
            [size_138] = segformer_eager.ops.pySize(size_argument4_1, Constant_55);
            [NumToTensor_width1_1] = segformer_eager.ops.makeStructForConstant(single(size_138.value), int64([size_138.rank]), "Tensor");
            [Int_142] = segformer_eager.ops.makeStructForConstant(NumToTensor_width1_1.value, int64([NumToTensor_width1_1.rank]), "Integer");

            [size_argument4_1_labelled] = segformer_eager.ops.labelWithPropagatedFormats(size_argument4_1, GetAttr_2_InputFormat1);
            [CallMethod_145,CallMethod_145_rank] = GetAttr_2.(predict)(size_argument4_1_labelled.value);
            [CallMethod_145, CallMethod_145_format] = segformer_eager.ops.permuteToReversePyTorch(CallMethod_145, '', int64(numel(CallMethod_145_rank)));
            if ~contains(CallMethod_145_format,'U')
                [CallMethod_145] = struct('value', CallMethod_145, 'rank', numel(CallMethod_145_format));
            else
                [CallMethod_145] = struct('value', CallMethod_145, 'rank', int64(max([2, ndims(CallMethod_145), numel(CallMethod_145_rank)])));
            end

            [transpose_encoderhiddenstate1_1] = segformer_eager.ops.pyTranspose(CallMethod_145, Constant_64, Constant_48);
            [ListConstruct_151] = segformer_eager.ops.pyListConstruct(Int_40, Constant_68, Int_136, Int_142);
            [reshape_input4_1] = segformer_eager.ops.pyView(transpose_encoderhiddenstate1_1, ListConstruct_151);
            [size_154] = segformer_eager.ops.pySize(size_argument2_1, Constant_48);
            [NumToTensor_155] = segformer_eager.ops.makeStructForConstant(single(size_154.value), int64([size_154.rank]), "Tensor");
            [Int_158] = segformer_eager.ops.makeStructForConstant(NumToTensor_155.value, int64([NumToTensor_155.rank]), "Integer");
            [size_160] = segformer_eager.ops.pySize(size_argument2_1, Constant_55);
            [NumToTensor_161] = segformer_eager.ops.makeStructForConstant(single(size_160.value), int64([size_160.rank]), "Tensor");
            [Int_166] = segformer_eager.ops.makeStructForConstant(NumToTensor_161.value, int64([NumToTensor_161.rank]), "Integer");
            [ListConstruct_167] = segformer_eager.ops.pyListConstruct(Int_158, Int_166);
            [upsamplebilinear2d_170] = segformer_eager.ops.pyUpsample2d(reshape_input4_1, 'linear', ListConstruct_167, Constant_88, Constant_89);
            [size_172] = segformer_eager.ops.pySize(size_argument1_1, Constant_48);
            [NumToTensor_height2_1] = segformer_eager.ops.makeStructForConstant(single(size_172.value), int64([size_172.rank]), "Tensor");
            [Int_176] = segformer_eager.ops.makeStructForConstant(NumToTensor_height2_1.value, int64([NumToTensor_height2_1.rank]), "Integer");
            [size_178] = segformer_eager.ops.pySize(size_argument1_1, Constant_55);
            [NumToTensor_width2_1] = segformer_eager.ops.makeStructForConstant(single(size_178.value), int64([size_178.rank]), "Tensor");
            [Int_182] = segformer_eager.ops.makeStructForConstant(NumToTensor_width2_1.value, int64([NumToTensor_width2_1.rank]), "Integer");

            size_argument1_1_labelled = size_argument1_1;
            size_argument1_1_labelled.value = permute(size_argument1_1_labelled.value, fliplr(1:max(2,size_argument1_1_labelled.rank)));
            [CallMethod_185,CallMethod_185_rank] = GetAttr_3.(predict)(size_argument1_1_labelled.value,dlarray(ones(1,size_argument1_1.rank),'UU'));
            [CallMethod_185, CallMethod_185_format] = segformer_eager.ops.permuteToReversePyTorch(CallMethod_185, '', int64(numel(CallMethod_185_rank)));
            if ~contains(CallMethod_185_format,'U')
                [CallMethod_185] = struct('value', CallMethod_185, 'rank', numel(CallMethod_185_format));
            else
                [CallMethod_185] = struct('value', CallMethod_185, 'rank', int64(max([2, ndims(CallMethod_185), numel(CallMethod_185_rank)])));
            end

            [transpose_encoderhiddenstate2_1] = segformer_eager.ops.pyTranspose(CallMethod_185, Constant_64, Constant_48);
            [ListConstruct_191] = segformer_eager.ops.pyListConstruct(Int_37, Constant_68, Int_176, Int_182);
            [reshape_input5_1] = segformer_eager.ops.pyView(transpose_encoderhiddenstate2_1, ListConstruct_191);
            [size_194] = segformer_eager.ops.pySize(size_argument2_1, Constant_48);
            [NumToTensor_195] = segformer_eager.ops.makeStructForConstant(single(size_194.value), int64([size_194.rank]), "Tensor");
            [Int_198] = segformer_eager.ops.makeStructForConstant(NumToTensor_195.value, int64([NumToTensor_195.rank]), "Integer");
            [size_200] = segformer_eager.ops.pySize(size_argument2_1, Constant_55);
            [NumToTensor_201] = segformer_eager.ops.makeStructForConstant(single(size_200.value), int64([size_200.rank]), "Tensor");
            [Int_206] = segformer_eager.ops.makeStructForConstant(NumToTensor_201.value, int64([NumToTensor_201.rank]), "Integer");
            [ListConstruct_207] = segformer_eager.ops.pyListConstruct(Int_198, Int_206);
            [upsamplebilinear2d_encoderhiddenstate3_1] = segformer_eager.ops.pyUpsample2d(reshape_input5_1, 'linear', ListConstruct_207, Constant_88, Constant_89);
            [ListConstruct_215] = segformer_eager.ops.pyListConstruct(upsamplebilinear2d_encoderhiddenstate3_1, upsamplebilinear2d_170, upsamplebilinear2d_130, upsamplebilinear2d_90);
            [cat_input6_1] = segformer_eager.ops.pyConcat(ListConstruct_215, Constant_64);

            [cat_input6_1_labelled] = segformer_eager.ops.labelWithPropagatedFormats(cat_input6_1, GetAttr_linearfuse_1_InputFormat1);
            [CallMethod_221] = GetAttr_linearfuse_1.(predict)(cat_input6_1_labelled.value);
            [CallMethod_221, CallMethod_221_format] = segformer_eager.ops.permuteToReversePyTorch(CallMethod_221, 'BCSS', '');
            if ~contains(CallMethod_221_format,'U')
                [CallMethod_221] = struct('value', CallMethod_221, 'rank', numel(CallMethod_221_format));
            else
                [CallMethod_221] = struct('value', CallMethod_221, 'rank', '');
            end


            [CallMethod_221_labelled] = segformer_eager.ops.labelWithPropagatedFormats(CallMethod_221, GetAttr_batchnorm_1_InputFormat1);
            [CallMethod_222] = GetAttr_batchnorm_1.(predict)(CallMethod_221_labelled.value);
            [CallMethod_222, CallMethod_222_format] = segformer_eager.ops.permuteToReversePyTorch(CallMethod_222, 'BCSS', '');
            if ~contains(CallMethod_222_format,'U')
                [CallMethod_222] = struct('value', CallMethod_222, 'rank', numel(CallMethod_222_format));
            else
                [CallMethod_222] = struct('value', CallMethod_222, 'rank', '');
            end


            [CallMethod_222_labelled] = segformer_eager.ops.labelWithPropagatedFormats(CallMethod_222, GetAttr_activation_1_InputFormat1);
            [CallMethod_226] = GetAttr_activation_1.(predict)(CallMethod_222_labelled.value);
            [CallMethod_226, CallMethod_226_format] = segformer_eager.ops.permuteToReversePyTorch(CallMethod_226, 'BCSS', '');
            if ~contains(CallMethod_226_format,'U')
                [CallMethod_226] = struct('value', CallMethod_226, 'rank', numel(CallMethod_226_format));
            else
                [CallMethod_226] = struct('value', CallMethod_226, 'rank', '');
            end


            [CallMethod_226_labelled] = segformer_eager.ops.labelWithPropagatedFormats(CallMethod_226, GetAttr_dropout_1_InputFormat1);
            [CallMethod_227] = GetAttr_dropout_1.(predict)(CallMethod_226_labelled.value);
            [CallMethod_227, CallMethod_227_format] = segformer_eager.ops.permuteToReversePyTorch(CallMethod_227, 'BCSS', '');
            if ~contains(CallMethod_227_format,'U')
                [CallMethod_227] = struct('value', CallMethod_227, 'rank', numel(CallMethod_227_format));
            else
                [CallMethod_227] = struct('value', CallMethod_227, 'rank', '');
            end


            [CallMethod_227_labelled] = segformer_eager.ops.labelWithPropagatedFormats(CallMethod_227, GetAttr_classifier_1_InputFormat1);
            [CallMethod_230] = GetAttr_classifier_1.(predict)(CallMethod_227_labelled.value);
            [CallMethod_230, CallMethod_230_format] = segformer_eager.ops.permuteToReversePyTorch(CallMethod_230, 'BCSS', '');
            if ~contains(CallMethod_230_format,'U')
                [CallMethod_230] = struct('value', CallMethod_230, 'rank', numel(CallMethod_230_format));
            else
                [CallMethod_230] = struct('value', CallMethod_230, 'rank', '');
            end

        end

    end
end

