classdef segformer_modelingsegformer_SegformerMLP < nnet.layer.Layer & nnet.layer.Formattable & ...
        nnet.layer.AutogeneratedFromPyTorch & nnet.layer.Acceleratable
    %segformer_modelingsegformer_SegformerMLP Auto-generated custom layer
    % Auto-generated by MATLAB on 04-Sep-2026 18:43:59

    properties (Learnable)
        % Networks (type dlnetwork)

        Param_proj
    end

    properties
        % Non-Trainable Parameters
        Constant_6
        Constant_5
        Constant_8



    end

    properties (Learnable)
        % Trainable Parameters

    end

    methods
        function obj = segformer_modelingsegformer_SegformerMLP(Name, Type, InputNames, OutputNames)
            obj.Name = Name;
            obj.Type = Type;
            obj.NumInputs = 1;
            obj.NumOutputs = 2;
            obj.InputNames = InputNames;
            obj.OutputNames = OutputNames;
        end

        function [CallMethod_12, CallMethod_12_rank] = predict(obj,flatten_argument1_1)

            %Use the input format inferred by the importer to permute the input into reverse-PyTorch dimension order
            [flatten_argument1_1, flatten_argument1_1_format] = segformer_eager.ops.permuteToReversePyTorch(flatten_argument1_1, '*CSS', '');

            if ~contains(flatten_argument1_1_format,'U')
                [flatten_argument1_1] = struct('value', flatten_argument1_1, 'rank', numel(flatten_argument1_1_format));
            end

            [CallMethod_12] = tracedPyTorchFunction(obj,flatten_argument1_1,false,"predict");

            [CallMethod_12_rank] = ones([1,CallMethod_12.rank], 'single');
            CallMethod_12_rank = dlarray(CallMethod_12_rank,'UU');
            %Permute U-labelled output to forward PyTorch dimension ordering
            if(isa(CallMethod_12.value,'dlarray') && any(dims(CallMethod_12.value) == 'U'))
                CallMethod_12 = permute(CallMethod_12.value, fliplr(1:max(2,CallMethod_12.rank)));
            else
                CallMethod_12 = dlarray(single(CallMethod_12.value), 'UU');
            end

        end



        function [CallMethod_12, CallMethod_12_rank] = forward(obj,flatten_argument1_1)

            %Use the input format inferred by the importer to permute the input into reverse-PyTorch dimension order
            [flatten_argument1_1, flatten_argument1_1_format] = segformer_eager.ops.permuteToReversePyTorch(flatten_argument1_1, '*CSS', '');

            if ~contains(flatten_argument1_1_format,'U')
                [flatten_argument1_1] = struct('value', flatten_argument1_1, 'rank', numel(flatten_argument1_1_format));
            end

            [CallMethod_12] = tracedPyTorchFunction(obj,flatten_argument1_1,true,"forward");

            [CallMethod_12_rank] = ones([1,CallMethod_12.rank], 'single');
            CallMethod_12_rank = dlarray(CallMethod_12_rank,'UU');
            %Permute U-labelled output to forward PyTorch dimension ordering
            if(isa(CallMethod_12.value,'dlarray') && any(dims(CallMethod_12.value) == 'U'))
                CallMethod_12 = permute(CallMethod_12.value, fliplr(1:max(2,CallMethod_12.rank)));
            else
                CallMethod_12 = dlarray(single(CallMethod_12.value), 'UU');
            end

        end



        function [CallMethod_12] = tracedPyTorchFunction(obj,flatten_argument1_1,isForward,predict)

            [Constant_6] = segformer_eager.ops.makeStructForConstant(int64(obj.Constant_6), int64(0), "Typed");
            [Constant_5] = segformer_eager.ops.makeStructForConstant(int64(obj.Constant_5), int64(0), "Typed");
            [Constant_8] = segformer_eager.ops.makeStructForConstant(int64(obj.Constant_8), int64(0), "Typed");
            GetAttr_proj_1 = obj.Param_proj;


            [flatten_7] = segformer_eager.ops.pyFlatten(flatten_argument1_1, Constant_5, Constant_6);
            [transpose_input_1] = segformer_eager.ops.pyTranspose(flatten_7, Constant_8, Constant_5);

            transpose_input_1_labelled = transpose_input_1;
            transpose_input_1_labelled.value = permute(transpose_input_1_labelled.value, fliplr(1:max(2,transpose_input_1_labelled.rank)));
            [CallMethod_12,CallMethod_12_rank] = GetAttr_proj_1.(predict)(transpose_input_1_labelled.value,dlarray(ones(1,transpose_input_1.rank),'UU'));
            [CallMethod_12, CallMethod_12_format] = segformer_eager.ops.permuteToReversePyTorch(CallMethod_12, '', int64(numel(CallMethod_12_rank)));
            if ~contains(CallMethod_12_format,'U')
                [CallMethod_12] = struct('value', CallMethod_12, 'rank', numel(CallMethod_12_format));
            else
                [CallMethod_12] = struct('value', CallMethod_12, 'rank', int64(max([2, ndims(CallMethod_12), numel(CallMethod_12_rank)])));
            end

        end

    end
end

