classdef segformer_modelingsegformer_SegformerAttention < nnet.layer.Layer & nnet.layer.Formattable & ...
        nnet.layer.AutogeneratedFromPyTorch
    %segformer_modelingsegformer_SegformerAttention Auto-generated custom layer
    % Auto-generated by MATLAB on 04-Sep-2026 18:43:31

    properties (Learnable)
        % Networks (type dlnetwork)

        Param_q_proj
        Param_sequence_reduction
        Param_k_proj
        Param_v_proj
        Param_o_proj
    end

    properties
        % Non-Trainable Parameters
        Constant_100
        Constant_98
        Constant_93
        Constant_15
        Constant_25
        Constant_39
        Constant_40
        Constant_44
        Constant_89
        Constant_96
        Constant_103



    end

    properties (Learnable)
        % Trainable Parameters

    end

    methods
        function obj = segformer_modelingsegformer_SegformerAttention(Name, Type, InputNames, OutputNames)
            obj.Name = Name;
            obj.Type = Type;
            obj.NumInputs = 6;
            obj.NumOutputs = 2;
            obj.InputNames = InputNames;
            obj.OutputNames = OutputNames;
        end

        function [CallMethod_123, CallMethod_123_rank] = predict(obj,size_argument1_1, CallMethod_argument2_1, CallMethod_argument3_1, size_argument1_1_rank, CallMethod_argument2_1_rank, CallMethod_argument3_1_rank)

            %Use the input format inferred by the importer to permute the input into reverse-PyTorch dimension order
            [size_argument1_1, size_argument1_1_format] = segformer_eager.ops.permuteToReversePyTorch(size_argument1_1, '', numel(size_argument1_1_rank));

            %Use the input format inferred by the importer to permute the input into reverse-PyTorch dimension order
            [CallMethod_argument2_1, CallMethod_argument2_1_format] = segformer_eager.ops.permuteToReversePyTorch(CallMethod_argument2_1, '', numel(CallMethod_argument2_1_rank));

            %Use the input format inferred by the importer to permute the input into reverse-PyTorch dimension order
            [CallMethod_argument3_1, CallMethod_argument3_1_format] = segformer_eager.ops.permuteToReversePyTorch(CallMethod_argument3_1, '', numel(CallMethod_argument3_1_rank));
            [size_argument1_1] = struct('value', size_argument1_1, 'rank', int64(max([2, ndims(size_argument1_1), numel(size_argument1_1_rank)])));
            [CallMethod_argument2_1] = struct('value', CallMethod_argument2_1, 'rank', int64(max([2, ndims(CallMethod_argument2_1), numel(CallMethod_argument2_1_rank)])));
            [CallMethod_argument3_1] = struct('value', CallMethod_argument3_1, 'rank', int64(max([2, ndims(CallMethod_argument3_1), numel(CallMethod_argument3_1_rank)])));

            [CallMethod_123] = tracedPyTorchFunction(obj,size_argument1_1, CallMethod_argument2_1, CallMethod_argument3_1,false,"predict");

            [CallMethod_123_rank] = ones([1,CallMethod_123.rank], 'single');
            CallMethod_123_rank = dlarray(CallMethod_123_rank,'UU');
            %Permute U-labelled output to forward PyTorch dimension ordering
            if(isa(CallMethod_123.value,'dlarray') && any(dims(CallMethod_123.value) == 'U'))
                CallMethod_123 = permute(CallMethod_123.value, fliplr(1:max(2,CallMethod_123.rank)));
            else
                CallMethod_123 = dlarray(single(CallMethod_123.value), 'UU');
            end

        end



        function [CallMethod_123, CallMethod_123_rank] = forward(obj,size_argument1_1, CallMethod_argument2_1, CallMethod_argument3_1, size_argument1_1_rank, CallMethod_argument2_1_rank, CallMethod_argument3_1_rank)

            %Use the input format inferred by the importer to permute the input into reverse-PyTorch dimension order
            [size_argument1_1, size_argument1_1_format] = segformer_eager.ops.permuteToReversePyTorch(size_argument1_1, '', numel(size_argument1_1_rank));

            %Use the input format inferred by the importer to permute the input into reverse-PyTorch dimension order
            [CallMethod_argument2_1, CallMethod_argument2_1_format] = segformer_eager.ops.permuteToReversePyTorch(CallMethod_argument2_1, '', numel(CallMethod_argument2_1_rank));

            %Use the input format inferred by the importer to permute the input into reverse-PyTorch dimension order
            [CallMethod_argument3_1, CallMethod_argument3_1_format] = segformer_eager.ops.permuteToReversePyTorch(CallMethod_argument3_1, '', numel(CallMethod_argument3_1_rank));
            [size_argument1_1] = struct('value', size_argument1_1, 'rank', int64(max([2, ndims(size_argument1_1), numel(size_argument1_1_rank)])));
            [CallMethod_argument2_1] = struct('value', CallMethod_argument2_1, 'rank', int64(max([2, ndims(CallMethod_argument2_1), numel(CallMethod_argument2_1_rank)])));
            [CallMethod_argument3_1] = struct('value', CallMethod_argument3_1, 'rank', int64(max([2, ndims(CallMethod_argument3_1), numel(CallMethod_argument3_1_rank)])));

            [CallMethod_123] = tracedPyTorchFunction(obj,size_argument1_1, CallMethod_argument2_1, CallMethod_argument3_1,true,"forward");

            [CallMethod_123_rank] = ones([1,CallMethod_123.rank], 'single');
            CallMethod_123_rank = dlarray(CallMethod_123_rank,'UU');
            %Permute U-labelled output to forward PyTorch dimension ordering
            if(isa(CallMethod_123.value,'dlarray') && any(dims(CallMethod_123.value) == 'U'))
                CallMethod_123 = permute(CallMethod_123.value, fliplr(1:max(2,CallMethod_123.rank)));
            else
                CallMethod_123 = dlarray(single(CallMethod_123.value), 'UU');
            end

        end



        function [CallMethod_123] = tracedPyTorchFunction(obj,size_argument1_1, CallMethod_argument2_1, CallMethod_argument3_1,isForward,predict)

            [Constant_100] = segformer_eager.ops.makeStructForConstant(double(obj.Constant_100), int64(0), "Typed");
            [Constant_98] = segformer_eager.ops.makeStructForConstant(int64(obj.Constant_98), int64(0), "Typed");
            [Constant_93] = segformer_eager.ops.makeStructForConstant(single(obj.Constant_93), int64([0]), "Tensor");
            [Constant_15] = segformer_eager.ops.makeStructForConstant(int64(obj.Constant_15), int64(0), "Typed");
            [Constant_25] = segformer_eager.ops.makeStructForConstant(int64(obj.Constant_25), int64(0), "Typed");
            [Constant_39] = segformer_eager.ops.makeStructForConstant(int64(obj.Constant_39), int64(0), "Typed");
            [Constant_40] = segformer_eager.ops.makeStructForConstant(int64(obj.Constant_40), int64(0), "Typed");
            [Constant_44] = segformer_eager.ops.makeStructForConstant(int64(obj.Constant_44), int64(0), "Typed");
            [Constant_89] = segformer_eager.ops.makeStructForConstant(int64(obj.Constant_89), int64(0), "Typed");
            [Constant_96] = segformer_eager.ops.makeStructForConstant(int64(obj.Constant_96), int64(0), "Typed");
            [Constant_103] = segformer_eager.ops.makeStructForConstant(single(obj.Constant_103), int64(0), "Typed");
            GetAttr_oproj_1 = obj.Param_o_proj;


            GetAttr_vproj_1 = obj.Param_v_proj;


            GetAttr_kproj_1 = obj.Param_k_proj;


            GetAttr_sequencereduction_1 = obj.Param_sequence_reduction;


            GetAttr_qproj_1 = obj.Param_q_proj;


            [size_16] = segformer_eager.ops.pySize(size_argument1_1, Constant_15);
            [NumToTensor_17] = segformer_eager.ops.makeStructForConstant(single(size_16.value), int64([size_16.rank]), "Tensor");
            [Int_20] = segformer_eager.ops.makeStructForConstant(NumToTensor_17.value, int64([NumToTensor_17.rank]), "Integer");
            [Int_23] = segformer_eager.ops.makeStructForConstant(NumToTensor_17.value, int64([NumToTensor_17.rank]), "Integer");
            [size_26] = segformer_eager.ops.pySize(size_argument1_1, Constant_25);
            [NumToTensor_27] = segformer_eager.ops.makeStructForConstant(single(size_26.value), int64([size_26.rank]), "Tensor");
            [Int_30] = segformer_eager.ops.makeStructForConstant(NumToTensor_27.value, int64([NumToTensor_27.rank]), "Integer");
            [Int_33] = segformer_eager.ops.makeStructForConstant(NumToTensor_27.value, int64([NumToTensor_27.rank]), "Integer");

            size_argument1_1_labelled = size_argument1_1;
            size_argument1_1_labelled.value = permute(size_argument1_1_labelled.value, fliplr(1:max(2,size_argument1_1_labelled.rank)));
            [CallMethod_36,CallMethod_36_rank] = GetAttr_qproj_1.(predict)(size_argument1_1_labelled.value,dlarray(ones(1,size_argument1_1.rank),'UU'));
            [CallMethod_36, CallMethod_36_format] = segformer_eager.ops.permuteToReversePyTorch(CallMethod_36, '', int64(numel(CallMethod_36_rank)));
            if ~contains(CallMethod_36_format,'U')
                [CallMethod_36] = struct('value', CallMethod_36, 'rank', numel(CallMethod_36_format));
            else
                [CallMethod_36] = struct('value', CallMethod_36, 'rank', int64(max([2, ndims(CallMethod_36), numel(CallMethod_36_rank)])));
            end

            % Int_23/Int_33 are derived via pySize on size_argument1_1, a
            % [batch=1, seq, channels] tensor - but MATLAB silently drops
            % a leading singleton (batch=1) dimension from the array's
            % actual storage, so pySize's dimension-index arithmetic
            % (which assumes the true logical rank) picks the wrong
            % axis entirely - confirmed by direct instrumentation
            % (batch came back as the seq_len value, seq came back as
            % the channel count). This is a different root cause than
            % the nested-network rank corruption fixed elsewhere: batch
            % is always exactly 1 here (one image/patch processed at a
            % time), so it's hardcoded; seq_len is derived directly from
            % size_argument1_1's own raw storage shape (the same reliable
            % source used a few lines below for the head-merge reshape),
            % not from a numel/head_dim computation, which silently
            % leaves the num_heads factor in whenever num_heads > 1.
            Int_23_fixed = Int_23; Int_23_fixed.value = int64(1);
            Int_33_fixed = Int_33; Int_33_fixed.value = int64(size(size_argument1_1.value, 2));
            [ListConstruct_41] = segformer_eager.ops.pyListConstruct(Int_23_fixed, Int_33_fixed, Constant_39, Constant_40);
            [view_42] = segformer_eager.ops.pyView(CallMethod_36, ListConstruct_41);
            [transpose_query_1] = segformer_eager.ops.pyTranspose(view_42, Constant_25, Constant_44);

            size_argument1_1_labelled = size_argument1_1;
            size_argument1_1_labelled.value = permute(size_argument1_1_labelled.value, fliplr(1:max(2,size_argument1_1_labelled.rank)));
            CallMethod_argument2_1_labelled = CallMethod_argument2_1;
            CallMethod_argument2_1_labelled.value = permute(CallMethod_argument2_1_labelled.value, fliplr(1:max(2,CallMethod_argument2_1_labelled.rank)));
            CallMethod_argument3_1_labelled = CallMethod_argument3_1;
            CallMethod_argument3_1_labelled.value = permute(CallMethod_argument3_1_labelled.value, fliplr(1:max(2,CallMethod_argument3_1_labelled.rank)));
            [CallMethod_50] = GetAttr_sequencereduction_1.(predict)(size_argument1_1_labelled.value,CallMethod_argument2_1_labelled.value,CallMethod_argument3_1_labelled.value,dlarray(ones(1,size_argument1_1.rank),'UU'),dlarray(ones(1,CallMethod_argument2_1.rank),'UU'),dlarray(ones(1,CallMethod_argument3_1.rank),'UU'));
            [CallMethod_50, CallMethod_50_format] = segformer_eager.ops.permuteToReversePyTorch(CallMethod_50, '', int64(3));
            if ~contains(CallMethod_50_format,'U')
                [CallMethod_50] = struct('value', CallMethod_50, 'rank', numel(CallMethod_50_format));
            else
                [CallMethod_50] = struct('value', CallMethod_50, 'rank', int64(3));
            end

            [size_52] = segformer_eager.ops.pySize(CallMethod_50, Constant_15);
            [NumToTensor_53] = segformer_eager.ops.makeStructForConstant(single(size_52.value), int64([size_52.rank]), "Tensor");
            [Int_56] = segformer_eager.ops.makeStructForConstant(NumToTensor_53.value, int64([NumToTensor_53.rank]), "Integer");
            [Int_59] = segformer_eager.ops.makeStructForConstant(NumToTensor_53.value, int64([NumToTensor_53.rank]), "Integer");
            [size_61] = segformer_eager.ops.pySize(CallMethod_50, Constant_25);
            [NumToTensor_62] = segformer_eager.ops.makeStructForConstant(single(size_61.value), int64([size_61.rank]), "Tensor");
            [Int_65] = segformer_eager.ops.makeStructForConstant(NumToTensor_62.value, int64([NumToTensor_62.rank]), "Integer");
            [Int_68] = segformer_eager.ops.makeStructForConstant(NumToTensor_62.value, int64([NumToTensor_62.rank]), "Integer");

            CallMethod_50_labelled = CallMethod_50;
            CallMethod_50_labelled.value = permute(CallMethod_50_labelled.value, fliplr(1:max(2,CallMethod_50_labelled.rank)));
            [CallMethod_71] = GetAttr_kproj_1.(predict)(CallMethod_50_labelled.value);
            [CallMethod_71, CallMethod_71_format] = segformer_eager.ops.permuteToReversePyTorch(CallMethod_71, '', int64(3));
            if ~contains(CallMethod_71_format,'U')
                [CallMethod_71] = struct('value', CallMethod_71, 'rank', numel(CallMethod_71_format));
            else
                [CallMethod_71] = struct('value', CallMethod_71, 'rank', int64(3));
            end

            [ListConstruct_74] = segformer_eager.ops.pyListConstruct(Int_59, Int_68, Constant_39, Constant_40);
            [view_75] = segformer_eager.ops.pyView(CallMethod_71, ListConstruct_74);
            [transpose_key_1] = segformer_eager.ops.pyTranspose(view_75, Constant_25, Constant_44);

            CallMethod_50_labelled = CallMethod_50;
            CallMethod_50_labelled.value = permute(CallMethod_50_labelled.value, fliplr(1:max(2,CallMethod_50_labelled.rank)));
            [CallMethod_80] = GetAttr_vproj_1.(predict)(CallMethod_50_labelled.value);
            [CallMethod_80, CallMethod_80_format] = segformer_eager.ops.permuteToReversePyTorch(CallMethod_80, '', int64(3));
            if ~contains(CallMethod_80_format,'U')
                [CallMethod_80] = struct('value', CallMethod_80, 'rank', numel(CallMethod_80_format));
            else
                [CallMethod_80] = struct('value', CallMethod_80, 'rank', int64(3));
            end

            [ListConstruct_83] = segformer_eager.ops.pyListConstruct(Int_56, Int_65, Constant_39, Constant_40);
            [view_84] = segformer_eager.ops.pyView(CallMethod_80, ListConstruct_83);
            [transpose_value_1] = segformer_eager.ops.pyTranspose(view_84, Constant_25, Constant_44);
            [transpose_90] = segformer_eager.ops.pyTranspose(transpose_key_1, Constant_44, Constant_89);
            [matmul_91] = segformer_eager.ops.pyMatmul(transpose_query_1, transpose_90);
            [mul_input_1] = segformer_eager.ops.pyElementwiseBinary(matmul_91, Constant_93, 'times');
            [softmax_97] = segformer_eager.ops.pySoftmax(mul_input_1, Constant_39);
            [to_input0_1] = segformer_eager.ops.pyToUnary(softmax_97, Constant_96, Constant_98, Constant_98, Constant_100);
            [dropout_attnweights_1] = segformer_eager.ops.pyDropout(to_input0_1, Constant_103, isForward);
            [matmul_attnoutput_1] = segformer_eager.ops.pyMatmul(dropout_attnweights_1, transpose_value_1);
            [transpose_110] = segformer_eager.ops.pyTranspose(matmul_attnoutput_1, Constant_25, Constant_44);
            contiguous_attnoutput0_1 = transpose_110;
            % Final head-merge reshape: Int_20/Int_30 (batch/channels via pySize
            % on size_argument1_1) are unreliable on this squeezed-batch tensor -
            % same root cause documented in SegformerSequenceReduction.m. batch is
            % always 1; seq_len derived directly from size_argument1_1 storage.
            Int_20.value = int64(1);
            Int_30.value = int64(size(size_argument1_1.value, 2));
            [ListConstruct_116] = segformer_eager.ops.pyListConstruct(Int_20, Int_30, Constant_39);
            [reshape_117] = segformer_eager.ops.pyView(contiguous_attnoutput0_1, ListConstruct_116);
            contiguous_input1_1 = reshape_117;

            contiguous_input1_1_labelled = contiguous_input1_1;
            contiguous_input1_1_labelled.value = permute(contiguous_input1_1_labelled.value, fliplr(1:max(2,contiguous_input1_1_labelled.rank)));
            [CallMethod_123,CallMethod_123_rank] = GetAttr_oproj_1.(predict)(contiguous_input1_1_labelled.value,dlarray(ones(1,contiguous_input1_1.rank),'UU'));
            [CallMethod_123, CallMethod_123_format] = segformer_eager.ops.permuteToReversePyTorch(CallMethod_123, '', int64(numel(CallMethod_123_rank)));
            if ~contains(CallMethod_123_format,'U')
                [CallMethod_123] = struct('value', CallMethod_123, 'rank', numel(CallMethod_123_format));
            else
                [CallMethod_123] = struct('value', CallMethod_123, 'rank', int64(max([2, ndims(CallMethod_123), numel(CallMethod_123_rank)])));
            end

        end

    end
end

