classdef segformer_modelingsegformer_SegformerStage < nnet.layer.Layer & nnet.layer.Formattable & ...
        nnet.layer.AutogeneratedFromPyTorch & nnet.layer.Acceleratable
    %segformer_modelingsegformer_SegformerStage Auto-generated custom layer
    % Auto-generated by MATLAB on 04-Sep-2026 18:43:35

    properties (Learnable)
        % Networks (type dlnetwork)

        Param_patch_embeddings
        Param_blocks_0
        Param_blocks_1
        Param_layer_norm
    end

    properties
        % Non-Trainable Parameters
        Constant_47
        Constant_56
        Constant_77



    end

    properties (Learnable)
        % Trainable Parameters

    end

    methods
        function obj = segformer_modelingsegformer_SegformerStage(Name, Type, InputNames, OutputNames)
            obj.Name = Name;
            obj.Type = Type;
            obj.NumInputs = 1;
            obj.NumOutputs = 1;
            obj.InputNames = InputNames;
            obj.OutputNames = OutputNames;
        end

        function [contiguous_input_1] = predict(obj,CallMethod_pixelvalues_1)
            if any(dims(CallMethod_pixelvalues_1) == 'U')
                %Validates that rank has been provided for U-labelled input
                segformer_eager.ops.validateInput(CallMethod_pixelvalues_1,'');
                [CallMethod_pixelvalues_1, CallMethod_pixelvalues_1_format] = segformer_eager.ops.permuteInputToReversePyTorch(CallMethod_pixelvalues_1, '');
            else

                %Use the input format inferred by the importer to permute the input into reverse-PyTorch dimension order
                [CallMethod_pixelvalues_1, CallMethod_pixelvalues_1_format] = segformer_eager.ops.permuteToReversePyTorch(CallMethod_pixelvalues_1, '*CSS', '');
            end

            if ~contains(CallMethod_pixelvalues_1_format,'U')
                [CallMethod_pixelvalues_1] = struct('value', CallMethod_pixelvalues_1, 'rank', numel(CallMethod_pixelvalues_1_format));
            end

            [contiguous_input_1] = tracedPyTorchFunction(obj,CallMethod_pixelvalues_1,false,"predict");


            [contiguous_input_1] = segformer_eager.ops.labelWithPropagatedFormats(contiguous_input_1, "*CSS");
            contiguous_input_1 = contiguous_input_1.value ;

        end



        function [contiguous_input_1] = forward(obj,CallMethod_pixelvalues_1)
            if any(dims(CallMethod_pixelvalues_1) == 'U')
                %Validates that rank has been provided for U-labelled input
                segformer_eager.ops.validateInput(CallMethod_pixelvalues_1,'');
                [CallMethod_pixelvalues_1, CallMethod_pixelvalues_1_format] = segformer_eager.ops.permuteInputToReversePyTorch(CallMethod_pixelvalues_1, '');
            else

                %Use the input format inferred by the importer to permute the input into reverse-PyTorch dimension order
                [CallMethod_pixelvalues_1, CallMethod_pixelvalues_1_format] = segformer_eager.ops.permuteToReversePyTorch(CallMethod_pixelvalues_1, '*CSS', '');
            end

            if ~contains(CallMethod_pixelvalues_1_format,'U')
                [CallMethod_pixelvalues_1] = struct('value', CallMethod_pixelvalues_1, 'rank', numel(CallMethod_pixelvalues_1_format));
            end

            [contiguous_input_1] = tracedPyTorchFunction(obj,CallMethod_pixelvalues_1,true,"forward");


            [contiguous_input_1] = segformer_eager.ops.labelWithPropagatedFormats(contiguous_input_1, "*CSS");
            contiguous_input_1 = contiguous_input_1.value ;

        end



        function [contiguous_input_1] = tracedPyTorchFunction(obj,CallMethod_pixelvalues_1,isForward,predict)

            [Constant_47] = segformer_eager.ops.makeStructForConstant(int64(obj.Constant_47), int64(0), "Typed");
            [Constant_56] = segformer_eager.ops.makeStructForConstant(int64(obj.Constant_56), int64(0), "Typed");
            GetAttr_layernorm_1 = obj.Param_layer_norm;


            GetAttr_1 = obj.Param_blocks_1;


            GetAttr_0 = obj.Param_blocks_0;


            GetAttr_patchembeddings_1 = obj.Param_patch_embeddings;

            GetAttr_patchembeddings_1_InputFormat1 = '*CSS';


            [CallMethod_pixelvalues_1_labelled] = segformer_eager.ops.labelWithPropagatedFormats(CallMethod_pixelvalues_1, GetAttr_patchembeddings_1_InputFormat1);
            [CallMethod_18,CallMethod_19,CallMethod_20,CallMethod_21,CallMethod_22,CallMethod_23,CallMethod_24,CallMethod_25,CallMethod_26,CallMethod_27,CallMethod_28,CallMethod_18_rank,CallMethod_19_rank,CallMethod_20_rank,CallMethod_21_rank,CallMethod_22_rank,CallMethod_23_rank,CallMethod_24_rank,CallMethod_25_rank,CallMethod_26_rank,CallMethod_27_rank,CallMethod_28_rank] = GetAttr_patchembeddings_1.(predict)(CallMethod_pixelvalues_1_labelled.value);
            [CallMethod_18, CallMethod_18_format] = segformer_eager.ops.permuteToReversePyTorch(CallMethod_18, '', int64(numel(CallMethod_18_rank)));[CallMethod_19, CallMethod_19_format] = segformer_eager.ops.permuteToReversePyTorch(CallMethod_19, '', int64(numel(CallMethod_19_rank)));[CallMethod_20, CallMethod_20_format] = segformer_eager.ops.permuteToReversePyTorch(CallMethod_20, '', int64(numel(CallMethod_20_rank)));[CallMethod_21, CallMethod_21_format] = segformer_eager.ops.permuteToReversePyTorch(CallMethod_21, '', int64(numel(CallMethod_21_rank)));[CallMethod_22, CallMethod_22_format] = segformer_eager.ops.permuteToReversePyTorch(CallMethod_22, '', int64(numel(CallMethod_22_rank)));[CallMethod_23, CallMethod_23_format] = segformer_eager.ops.permuteToReversePyTorch(CallMethod_23, '', int64(numel(CallMethod_23_rank)));[CallMethod_24, CallMethod_24_format] = segformer_eager.ops.permuteToReversePyTorch(CallMethod_24, '', int64(numel(CallMethod_24_rank)));[CallMethod_25, CallMethod_25_format] = segformer_eager.ops.permuteToReversePyTorch(CallMethod_25, '', int64(numel(CallMethod_25_rank)));[CallMethod_26, CallMethod_26_format] = segformer_eager.ops.permuteToReversePyTorch(CallMethod_26, '', int64(numel(CallMethod_26_rank)));[CallMethod_27, CallMethod_27_format] = segformer_eager.ops.permuteToReversePyTorch(CallMethod_27, '', int64(numel(CallMethod_27_rank)));[CallMethod_28, CallMethod_28_format] = segformer_eager.ops.permuteToReversePyTorch(CallMethod_28, '', int64(numel(CallMethod_28_rank)));
            if ~contains(CallMethod_18_format,'U')
                [CallMethod_18] = struct('value', CallMethod_18, 'rank', numel(CallMethod_18_format));
            else
                [CallMethod_18] = struct('value', CallMethod_18, 'rank', int64(max([2, ndims(CallMethod_18), numel(CallMethod_18_rank)])));
            end
            if ~contains(CallMethod_19_format,'U')
                [CallMethod_19] = struct('value', CallMethod_19, 'rank', numel(CallMethod_19_format));
            else
                [CallMethod_19] = struct('value', CallMethod_19, 'rank', int64(max([2, ndims(CallMethod_19), numel(CallMethod_19_rank)])));
            end
            if ~contains(CallMethod_20_format,'U')
                [CallMethod_20] = struct('value', CallMethod_20, 'rank', numel(CallMethod_20_format));
            else
                [CallMethod_20] = struct('value', CallMethod_20, 'rank', int64(max([2, ndims(CallMethod_20), numel(CallMethod_20_rank)])));
            end
            if ~contains(CallMethod_21_format,'U')
                [CallMethod_21] = struct('value', CallMethod_21, 'rank', numel(CallMethod_21_format));
            else
                [CallMethod_21] = struct('value', CallMethod_21, 'rank', int64(max([2, ndims(CallMethod_21), numel(CallMethod_21_rank)])));
            end
            if ~contains(CallMethod_22_format,'U')
                [CallMethod_22] = struct('value', CallMethod_22, 'rank', numel(CallMethod_22_format));
            else
                [CallMethod_22] = struct('value', CallMethod_22, 'rank', int64(max([2, ndims(CallMethod_22), numel(CallMethod_22_rank)])));
            end
            if ~contains(CallMethod_23_format,'U')
                [CallMethod_23] = struct('value', CallMethod_23, 'rank', numel(CallMethod_23_format));
            else
                [CallMethod_23] = struct('value', CallMethod_23, 'rank', int64(max([2, ndims(CallMethod_23), numel(CallMethod_23_rank)])));
            end
            if ~contains(CallMethod_24_format,'U')
                [CallMethod_24] = struct('value', CallMethod_24, 'rank', numel(CallMethod_24_format));
            else
                [CallMethod_24] = struct('value', CallMethod_24, 'rank', int64(max([2, ndims(CallMethod_24), numel(CallMethod_24_rank)])));
            end
            if ~contains(CallMethod_25_format,'U')
                [CallMethod_25] = struct('value', CallMethod_25, 'rank', numel(CallMethod_25_format));
            else
                [CallMethod_25] = struct('value', CallMethod_25, 'rank', int64(max([2, ndims(CallMethod_25), numel(CallMethod_25_rank)])));
            end
            if ~contains(CallMethod_26_format,'U')
                [CallMethod_26] = struct('value', CallMethod_26, 'rank', numel(CallMethod_26_format));
            else
                [CallMethod_26] = struct('value', CallMethod_26, 'rank', int64(max([2, ndims(CallMethod_26), numel(CallMethod_26_rank)])));
            end
            if ~contains(CallMethod_27_format,'U')
                [CallMethod_27] = struct('value', CallMethod_27, 'rank', numel(CallMethod_27_format));
            else
                [CallMethod_27] = struct('value', CallMethod_27, 'rank', int64(max([2, ndims(CallMethod_27), numel(CallMethod_27_rank)])));
            end
            if ~contains(CallMethod_28_format,'U')
                [CallMethod_28] = struct('value', CallMethod_28, 'rank', numel(CallMethod_28_format));
            else
                [CallMethod_28] = struct('value', CallMethod_28, 'rank', int64(max([2, ndims(CallMethod_28), numel(CallMethod_28_rank)])));
            end


            CallMethod_18_labelled = CallMethod_18;
            CallMethod_18_labelled.value = permute(CallMethod_18_labelled.value, fliplr(1:max(2,CallMethod_18_labelled.rank)));
            CallMethod_19_labelled = CallMethod_19;
            CallMethod_19_labelled.value = permute(CallMethod_19_labelled.value, fliplr(1:max(2,CallMethod_19_labelled.rank)));
            CallMethod_20_labelled = CallMethod_20;
            CallMethod_20_labelled.value = permute(CallMethod_20_labelled.value, fliplr(1:max(2,CallMethod_20_labelled.rank)));
            CallMethod_21_labelled = CallMethod_21;
            CallMethod_21_labelled.value = permute(CallMethod_21_labelled.value, fliplr(1:max(2,CallMethod_21_labelled.rank)));
            CallMethod_22_labelled = CallMethod_22;
            CallMethod_22_labelled.value = permute(CallMethod_22_labelled.value, fliplr(1:max(2,CallMethod_22_labelled.rank)));
            [CallMethod_35,CallMethod_35_rank] = GetAttr_0.(predict)(CallMethod_18_labelled.value,CallMethod_19_labelled.value,CallMethod_20_labelled.value,CallMethod_21_labelled.value,CallMethod_22_labelled.value,dlarray(ones(1,CallMethod_18.rank),'UU'),dlarray(ones(1,CallMethod_19.rank),'UU'),dlarray(ones(1,CallMethod_20.rank),'UU'),dlarray(ones(1,CallMethod_21.rank),'UU'),dlarray(ones(1,CallMethod_22.rank),'UU'));
            [CallMethod_35, CallMethod_35_format] = segformer_eager.ops.permuteToReversePyTorch(CallMethod_35, '', int64(numel(CallMethod_35_rank)));
            if ~contains(CallMethod_35_format,'U')
                [CallMethod_35] = struct('value', CallMethod_35, 'rank', numel(CallMethod_35_format));
            else
                [CallMethod_35] = struct('value', CallMethod_35, 'rank', int64(max([2, ndims(CallMethod_35), numel(CallMethod_35_rank)])));
            end


            CallMethod_35_labelled = CallMethod_35;
            CallMethod_35_labelled.value = permute(CallMethod_35_labelled.value, fliplr(1:max(2,CallMethod_35_labelled.rank)));
            CallMethod_23_labelled = CallMethod_23;
            CallMethod_23_labelled.value = permute(CallMethod_23_labelled.value, fliplr(1:max(2,CallMethod_23_labelled.rank)));
            CallMethod_24_labelled = CallMethod_24;
            CallMethod_24_labelled.value = permute(CallMethod_24_labelled.value, fliplr(1:max(2,CallMethod_24_labelled.rank)));
            CallMethod_25_labelled = CallMethod_25;
            CallMethod_25_labelled.value = permute(CallMethod_25_labelled.value, fliplr(1:max(2,CallMethod_25_labelled.rank)));
            CallMethod_26_labelled = CallMethod_26;
            CallMethod_26_labelled.value = permute(CallMethod_26_labelled.value, fliplr(1:max(2,CallMethod_26_labelled.rank)));
            [CallMethod_42,CallMethod_42_rank] = GetAttr_1.(predict)(CallMethod_35_labelled.value,CallMethod_23_labelled.value,CallMethod_24_labelled.value,CallMethod_25_labelled.value,CallMethod_26_labelled.value,dlarray(ones(1,CallMethod_35.rank),'UU'),dlarray(ones(1,CallMethod_23.rank),'UU'),dlarray(ones(1,CallMethod_24.rank),'UU'),dlarray(ones(1,CallMethod_25.rank),'UU'),dlarray(ones(1,CallMethod_26.rank),'UU'));
            [CallMethod_42, CallMethod_42_format] = segformer_eager.ops.permuteToReversePyTorch(CallMethod_42, '', int64(numel(CallMethod_42_rank)));
            if ~contains(CallMethod_42_format,'U')
                [CallMethod_42] = struct('value', CallMethod_42, 'rank', numel(CallMethod_42_format));
            else
                [CallMethod_42] = struct('value', CallMethod_42, 'rank', int64(max([2, ndims(CallMethod_42), numel(CallMethod_42_rank)])));
            end


            CallMethod_42_labelled = CallMethod_42;
            CallMethod_42_labelled.value = permute(CallMethod_42_labelled.value, fliplr(1:max(2,CallMethod_42_labelled.rank)));
            [CallMethod_45,CallMethod_45_rank] = GetAttr_layernorm_1.(predict)(CallMethod_42_labelled.value,dlarray(ones(1,CallMethod_42.rank),'UU'));
            [CallMethod_45, CallMethod_45_format] = segformer_eager.ops.permuteToReversePyTorch(CallMethod_45, '', int64(numel(CallMethod_45_rank)));
            if ~contains(CallMethod_45_format,'U')
                [CallMethod_45] = struct('value', CallMethod_45, 'rank', numel(CallMethod_45_format));
            else
                [CallMethod_45] = struct('value', CallMethod_45, 'rank', int64(max([2, ndims(CallMethod_45), numel(CallMethod_45_rank)])));
            end

            [size_48] = segformer_eager.ops.pySize(CallMethod_45, Constant_47);
            [NumToTensor_batchsize_1] = segformer_eager.ops.makeStructForConstant(single(size_48.value), int64([size_48.rank]), "Tensor");
            [Int_53] = segformer_eager.ops.makeStructForConstant(NumToTensor_batchsize_1.value, int64([NumToTensor_batchsize_1.rank]), "Integer");
            [ListConstruct_57] = segformer_eager.ops.pyListConstruct(Int_53, CallMethod_27, CallMethod_28, Constant_56);
            [reshape_58] = segformer_eager.ops.pyView(CallMethod_45, ListConstruct_57);
            [Constant_77] = segformer_eager.ops.makeStructForConstant(int64(obj.Constant_77), int64(1), "Typed");
            [permute_64] = segformer_eager.ops.pyPermute(reshape_58, Constant_77);
            contiguous_input_1 = permute_64;
        end

    end
end

