function reportPath = generateAnnotatedReport(rgbImage, enhImg, qc, trackAResult, trackBResult, ...
    gradeResult, camResult, overlapResult, patientInfo, imageId, reportPath)
%GENERATEANNOTATEDREPORT Module 4: build the final clinical report as a PDF.
%   reportPath = generateAnnotatedReport(rgbImage, enhImg, qc, trackAResult,
%       trackBResult, gradeResult, camResult, overlapResult, patientInfo,
%       imageId, reportPath)
%
%   Renders real HTML/CSS (matching the web app's ReportPage.tsx layout
%   and styling - same section numbering, pill badges, InfoGrid,
%   findings table) and converts it to PDF via headless Microsoft Edge
%   (--print-to-pdf). Earlier versions hand-positioned MATLAB text()/
%   rectangle() calls at manually-tuned normalized coordinates -
%   workable in principle, but every pass at "make it look professional"
%   kept surfacing new spacing/alignment misses, because that approach
%   has no real layout engine behind it. HTML/CSS is what actually
%   produces the reference look (it IS how the web report is rendered),
%   so this generates the same kind of document the same way instead of
%   approximating it by hand.
%
%   Built as small per-section HTML fragments (buildXSectionHtml below),
%   each its own sprintf call with only its own arguments, rather than
%   one giant format string - a single 30+ argument sprintf is exactly
%   the kind of thing that silently misaligns (wrong value in wrong
%   table cell) with no error to catch it.
%
%   Section structure mirrors ReportPage.tsx directly: 1 Recommendation,
%   2 Retinal Findings (image + findings table), 3 DR Severity
%   Assessment, 4 AI Analysis Visualizations (segmentation overlay +
%   Grad-CAM + color legend) - plus a MATLAB-report-only Grading Reasons
%   detail table and Technical Appendix. Per-lesion location/count/
%   reliability come from the shared buildLesionFindings.m so the two
%   report surfaces can't silently disagree.
%
%   patientInfo (all optional - pass [] or omit fields for "Unknown"):
%     .diabetesControl / .diabetesDurationYears / .hba1c / .patientId
%
%   Requires Microsoft Edge installed locally (bundled with Windows).
%
%   See also: gradeImage, computeGradCAM, lesionAttentionOverlap,
%   calibrateConfidence, categorizeReliability, getFollowUpRecommendation,
%   buildLesionFindings, buildLesionOverlay.

    if nargin < 9 || isempty(patientInfo)
        patientInfo = struct();
    end
    if nargin < 10 || isempty(imageId)
        imageId = 'unknown';
    end
    if nargin < 11 || isempty(reportPath)
        reportPath = fullfile('results', sprintf('report_%s.pdf', imageId));
    end

    flag = gradeResult.flag;
    calibConf = calibrateConfidence(gradeResult.cnn.rawConfidence);
    reliabilityCategory = categorizeReliability(calibConf);
    followUp = getFollowUpRecommendation(gradeResult.shownGrade, flag.flagged);
    findings = buildLesionFindings(trackAResult, trackBResult);
    lesionOverlay = buildLesionOverlay(enhImg, trackAResult, trackBResult);

    body = [ ...
        headerAndPatientHtml(imageId, patientInfo), ...
        recommendationSectionHtml(gradeResult, flag, followUp), ...
        findingsSectionHtml(rgbImage, qc, findings), ...
        '<div class="page-break"></div>', ...
        severitySectionHtml(gradeResult, flag), ...
        visualizationsSectionHtml(lesionOverlay, camResult), ...
        '<div class="page-break"></div>', ...
        reasonsAndAppendixHtml(trackAResult, trackBResult, gradeResult, flag, calibConf, reliabilityCategory, overlapResult), ...
        footerHtml() ...
    ];

    html = ['<!DOCTYPE html><html><head><meta charset="utf-8"><style>' reportCss() '</style></head><body>' body '</body></html>'];
    reportPath = renderHtmlToPdf(html, reportPath);
end

% ============================================================
% HTML -> PDF via headless Edge
% ============================================================

function reportPath = renderHtmlToPdf(html, reportPath)
    edgeCandidates = {
        'C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe'
        'C:\Program Files\Microsoft\Edge\Application\msedge.exe'
    };
    edgeExe = '';
    for i = 1:numel(edgeCandidates)
        if isfile(edgeCandidates{i})
            edgeExe = edgeCandidates{i};
            break
        end
    end
    if isempty(edgeExe)
        error('generateAnnotatedReport:noEdge', ...
            'Microsoft Edge not found at either standard install location - needed to render the HTML report to PDF.');
    end

    outDir = fileparts(reportPath);
    if ~isempty(outDir) && ~isfolder(outDir)
        mkdir(outDir);
    end
    % A fixed, readable filename rather than a random tempname() - Edge's
    % headless print always stamps a timestamp + source URL header/footer
    % on every page (matching the reference report, itself a browser
    % print - --print-to-pdf-no-header does not suppress this on the
    % installed Edge build, tested directly), so what that footer shows
    % actually matters instead of being a throwaway path.
    renderDir = fullfile(outDir, '.report_render');
    if ~isfolder(renderDir)
        mkdir(renderDir);
    end
    htmlPath = fullfile(renderDir, 'report_preview.html');
    fid = fopen(htmlPath, 'w', 'n', 'UTF-8');
    fwrite(fid, html, 'char');
    fclose(fid);

    if isfile(reportPath)
        delete(reportPath);
    end
    cmd = sprintf('"%s" --headless --disable-gpu --no-sandbox --print-to-pdf="%s" --print-to-pdf-no-header "file:///%s"', ...
        edgeExe, reportPath, strrep(htmlPath, '\', '/'));
    [status, cmdOut] = system(cmd);
    delete(htmlPath);
    if status ~= 0 || ~isfile(reportPath)
        error('generateAnnotatedReport:renderFailed', 'Edge headless PDF render failed: %s', cmdOut);
    end
end

function uri = imageToDataUri(img)
%IMAGETODATAURI JPEG-encode an image in memory and return a base64
%data: URI, so the HTML report is one self-contained file with no
%external image references for Edge headless to resolve.
    tmp = [tempname() '.jpg'];
    imwrite(im2uint8(img), tmp, 'Quality', 85);
    fid = fopen(tmp, 'r');
    bytes = fread(fid, Inf, 'uint8=>uint8');
    fclose(fid);
    delete(tmp);
    uri = ['data:image/jpeg;base64,' matlab.net.base64encode(bytes)];
end

% ============================================================
% Section builders - each a self-contained sprintf with only its own args
% ============================================================

function h = headerAndPatientHtml(imageId, patientInfo)
    h = [ ...
        '<div class="brand-row"><div class="brand-left"><div class="brand-mark">DS</div>' ...
        '<div><div class="brand-title">Diabetic Retinopathy Screening Report</div>' ...
        '<div class="brand-sub">AI-Assisted Automated Fundus Analysis</div></div></div>' ...
        sprintf('<div class="meta-right"><b>Image ID:</b> %s<br>Date: %s</div></div>', ...
            htmlEscape(imageId), datestr(now, 'mm/dd/yyyy')) ... %#ok<TNOW1,DATST>
        '<hr class="top">' ...
        '<div class="patient-grid">' ...
        infoField('Patient ID', htmlEscape(valueOrUnknown(patientInfo, 'patientId', '%s'))) ...
        infoField('Diabetes Control', htmlEscape(valueOrUnknown(patientInfo, 'diabetesControl', '%s'))) ...
        infoField('Duration of Diabetes', htmlEscape(valueOrUnknown(patientInfo, 'diabetesDurationYears', '%g years'))) ...
        infoField('HbA1c', htmlEscape(valueOrUnknown(patientInfo, 'hba1c', '%.1f%%'))) ...
        '</div>' ...
    ];
end

function h = infoField(label, value)
    h = sprintf('<div><div class="field-label">%s</div><div class="field-value">%s</div></div>', ...
        htmlEscape(label), value);
end

function h = sectionHead(number, title)
    h = sprintf(['<div class="section-head"><span class="section-num">%s</span>' ...
        '<span class="section-title">%s</span></div><hr class="section-rule">'], number, htmlEscape(title));
end

function h = recommendationSectionHtml(gradeResult, flag, followUp)
    resultCategory = resultCategoryOf(gradeResult);
    [pillClass, planClass] = toneClasses(resultCategory);

    disagreeHtml = '';
    if flag.flagged
        bannerText = ternary(strcmp(flag.priority, 'high'), ...
            'High-risk lesion pattern requires specialist confirmation.', ...
            'Possible false alarm - specialist confirmation recommended.');
        disagreeHtml = sprintf([ ...
            '<div class="disagree-banner"><div class="disagree-title">&#9888; Automated Opinions Disagree</div>' ...
            '<div class="disagree-body">%s</div></div>'], htmlEscape(bannerText));
    end

    h = [ ...
        '<div class="section">' sectionHead('1', 'Recommendation') ...
        sprintf('<span class="pill %s">%s</span>', pillClass, resultCategory) ...
        sprintf(['<div class="plan-box %s"><div class="plan-label">Recommended Clinical Action Plan</div>' ...
            '<div class="plan-text">%s</div></div>'], planClass, htmlEscape(followUp)) ...
        disagreeHtml ...
        '</div>' ...
    ];
end

function h = findingsSectionHtml(rgbImage, qc, findings)
    origUri = imageToDataUri(rgbImage);
    qualityLabel = qualityCategoryLabel(qc.decision);
    qualityClass = ternary(strcmp(char(qc.decision), 'Pass'), 'routine', ...
        ternary(strcmp(char(qc.decision), 'Reject'), 'priority', 'review'));

    rowsHtml = '';
    for i = 1:numel(findings)
        f = findings(i);
        rowsHtml = [rowsHtml sprintf([ ...
            '<tr><td class="lt">%s</td><td>%d</td><td class="loc">%s</td>' ...
            '<td><span class="conf %s">%s</span></td></tr>'], ...
            htmlEscape(f.lesionType), f.count, htmlEscape(f.location), ...
            reliabilityClass(f.reliabilityCategory), f.reliabilityCategory)]; %#ok<AGROW>
    end
    if isempty(findings)
        rowsHtml = '<tr><td colspan="4" class="empty">No lesions detected above the reporting threshold.</td></tr>';
    end

    h = [ ...
        '<div class="section">' sectionHead('2', 'Retinal Findings') ...
        '<div class="findings-row"><div>' ...
        sprintf('<div class="fundus-box"><img src="%s"></div>', origUri) ...
        sprintf('<div class="quality-pill-row"><span class="pill %s">Overall Quality: %s</span></div>', ...
            qualityClass, qualityLabel) ...
        '</div>' ...
        sprintf(['<div style="flex:1;"><table class="findings"><thead><tr>' ...
            '<th>Lesion Type</th><th>Count</th><th>Location</th><th>Confidence</th>' ...
            '</tr></thead><tbody>%s</tbody></table></div>'], rowsHtml) ...
        '</div></div>' ...
    ];
end

function h = severitySectionHtml(gradeResult, flag)
    referableClass = ternary(gradeResult.isReferable, 'danger', 'success');
    agreementClass = ternary(~flag.flagged, 'success', 'warn');
    h = [ ...
        '<div class="section">' sectionHead('3', 'DR Severity Assessment') ...
        '<div class="infogrid">' ...
        infoField('ICDR Severity Grade', sprintf('Grade %d - %s', gradeResult.shownGrade, htmlEscape(gradeLabel(gradeResult.shownGrade)))) ...
        sprintf('<div><div class="field-label">Referable DR</div><div class="field-value val %s">%s</div></div>', ...
            referableClass, ternary(gradeResult.isReferable, 'YES', 'NO')) ...
        infoField('Grading Pathway', ternary(gradeResult.rule.committed, 'Rule-based', 'CNN')) ...
        sprintf('<div><div class="field-label">Rule / CNN Agreement</div><div class="field-value val %s">%s</div></div>', ...
            agreementClass, ternary(~flag.flagged, 'Agree', 'Disagreement - flagged')) ...
        '</div></div>' ...
    ];
end

function h = visualizationsSectionHtml(lesionOverlay, camResult)
    segUri = imageToDataUri(lesionOverlay);
    camUri = imageToDataUri(camResult.overlayImage);
    legendItems = {
        '#ff0000' 'Vessel'; '#ffffff' 'Optic Disc'; '#00ff00' 'Fovea'; '#ffff00' 'Hard Exudates'; ...
        '#00ffff' 'Hemorrhages'; '#0000ff' 'Cotton Wool Spots'; '#ff8c00' 'Vitreous Hemorrhage'; ...
        '#ff4500' 'IRMA'; '#ff00ff' 'Neovascularization / confirmed MA (X)';
    };
    legendHtml = '';
    for i = 1:size(legendItems, 1)
        legendHtml = [legendHtml sprintf('<div><span class="swatch" style="background:%s"></span>%s</div>', ...
            legendItems{i,1}, htmlEscape(legendItems{i,2}))]; %#ok<AGROW>
    end

    h = [ ...
        '<div class="section">' sectionHead('4', 'AI Analysis Visualizations') ...
        '<div class="viz-row"><div class="viz-col">' ...
        sprintf('<img src="%s">', segUri) ...
        '<div class="viz-caption">AI-Interpreted Image (lesion overlay)</div>' ...
        sprintf('<div class="legend">%s</div>', legendHtml) ...
        '</div><div class="viz-col">' ...
        sprintf('<img src="%s">', camUri) ...
        '<div class="viz-caption">Grad-CAM Attention Heatmap</div>' ...
        '</div></div></div>' ...
    ];
end

function h = reasonsAndAppendixHtml(trackAResult, trackBResult, gradeResult, flag, calibConf, reliabilityCategory, overlapResult)
    rowsHtml = '';
    ignoredClasses = {'Background', 'Retina'};
    for i = 1:numel(trackAResult.classNames)
        name = trackAResult.classNames{i};
        if any(strcmp(name, ignoredClasses)), continue; end
        fieldName = matlab.lang.makeValidName(name);
        pixelCount = nnz(trackAResult.masks.(fieldName));
        detected = ternary(pixelCount > 25, 'Yes', 'No');
        detail = ternary(pixelCount > 25, sprintf('%d px region', pixelCount), '-');
        rowsHtml = [rowsHtml sprintf('<tr><td>%s</td><td>%s</td><td>%s</td></tr>', ...
            htmlEscape(name), detected, htmlEscape(detail))]; %#ok<AGROW>
    end
    maDetected = ternary(trackBResult.confirmedCount > 0, 'Yes', ternary(trackBResult.hasAmbiguous, 'Ambiguous', 'No'));
    maDetail = sprintf('%d confirmed, %s ambiguous candidate(s)', trackBResult.confirmedCount, ...
        ternary(trackBResult.hasAmbiguous, 'has', 'no'));
    rowsHtml = [rowsHtml sprintf('<tr><td>Microaneurysms</td><td>%s</td><td>%s</td></tr>', maDetected, htmlEscape(maDetail))];

    noteHtml = '';
    if overlapResult.hasUnexplainedRegion
        noteHtml = '<p class="note-warn">Note: Grad-CAM highlights a region Module 2 did not flag - worth a second look.</p>';
    end

    h = [ ...
        '<div class="section">' sectionHead('5', 'Grading Reasons (Detail)') ...
        sprintf(['<table class="reasons"><thead><tr><th>Finding</th><th>Detected</th><th>Detail</th></tr></thead>' ...
            '<tbody>%s</tbody></table>'], rowsHtml) ...
        '<div class="reasoning-block">' ...
        '<div class="reasoning-label">Rule-based path (Module 2 findings):</div>' ...
        sprintf('<div>%s</div>', htmlEscape(gradeResult.rule.reason)) ...
        sprintf('<div class="reasoning-label">Deep-learning grading model: Grade %d</div>', gradeResult.cnn.grade) ...
        sprintf('<div class="reasoning-label">Final shown grade: %d</div>', gradeResult.shownGrade) ...
        sprintf('<div>%s</div>', htmlEscape(flag.message)) ...
        '</div>' ...
        '<div class="reasoning-block"><div class="reasoning-label">Technical Appendix</div>' ...
        '<div class="infogrid" style="margin-top:8px;">' ...
        infoField('Calibrated Confidence', sprintf('%.0f%% (%s)', calibConf * 100, reliabilityCategory)) ...
        infoField('Lesion-Attention Overlap', sprintf('%.0f%%', overlapResult.overlapScore * 100)) ...
        infoField('CNN Continuous Score', sprintf('%.2f / 4', gradeResult.cnn.continuousScore)) ...
        infoField('CNN Raw Confidence', sprintf('%.2f (uncalibrated)', gradeResult.cnn.rawConfidence)) ...
        '</div>' noteHtml '</div></div>' ...
    ];
end

function h = footerHtml()
    h = [ ...
        '<div class="disclaimer">This report is generated by an AI-assisted screening pipeline and is intended as a ' ...
        'decision-support aid for referral triage only. It does not constitute a comprehensive ophthalmic examination ' ...
        'or final diagnosis. All findings require confirmation by a qualified ophthalmologist before any clinical ' ...
        'decision is made.</div>' ...
        '<div class="footer-row"><div style="max-width:340px; font-size:10px; color:#8792a1;">' ...
        'For specialist referral cases, please report to the designated district hospital ophthalmology unit.</div>' ...
        '<div class="signature"><div class="line"></div>Health Worker Signature</div></div>' ...
    ];
end

function css = reportCss()
    css = [ ...
'@page { size: A4; margin: 14mm 16mm; }' ...
'* { box-sizing: border-box; }' ...
'body { font-family: -apple-system, "Segoe UI", Arial, sans-serif; color: #1b2430; font-size: 12px; line-height: 1.5; margin: 0; }' ...
'.brand-row { display: flex; align-items: center; justify-content: space-between; margin-bottom: 6px; }' ...
'.brand-left { display: flex; align-items: center; gap: 10px; }' ...
'.brand-mark { width: 34px; height: 34px; border-radius: 8px; background: #064e47; color: #fff; font-weight: 700; font-size: 14px; display: flex; align-items: center; justify-content: center; }' ...
'.brand-title { font-size: 20px; font-weight: 700; color: #0f172a; }' ...
'.brand-sub { font-size: 10.5px; color: #64748b; font-style: italic; margin-top: 1px; }' ...
'.meta-right { text-align: right; font-size: 10.5px; color: #64748b; }' ...
'.meta-right b { color: #1b2430; }' ...
'hr.top { border: none; border-top: 2px solid #1b2430; margin: 10px 0 16px; }' ...
'.patient-grid { display: grid; grid-template-columns: repeat(4, 1fr); gap: 12px; margin-bottom: 22px; }' ...
'.field-label { font-size: 9.5px; text-transform: uppercase; letter-spacing: 0.04em; color: #8792a1; font-weight: 700; }' ...
'.field-value { font-size: 13px; font-weight: 700; color: #1b2430; margin-top: 2px; }' ...
'.section { margin-bottom: 22px; }' ...
'.section-head { display: flex; align-items: baseline; gap: 10px; margin-bottom: 10px; }' ...
'.section-num { background: #eef1f5; color: #8792a1; font-size: 10px; font-weight: 700; border-radius: 4px; padding: 2px 7px; }' ...
'.section-title { font-size: 13px; font-weight: 700; text-transform: uppercase; letter-spacing: 0.02em; }' ...
'.section-rule { border: none; border-top: 1.5px solid #1b2430; margin: 8px 0 14px; }' ...
'.pill { display: inline-block; border: 1.5px solid; border-radius: 999px; padding: 6px 20px; font-weight: 700; font-size: 12.5px; background: #fff; }' ...
'.pill.priority { color: #c11d3f; border-color: #c11d3f; } .pill.review { color: #b56a08; border-color: #b56a08; } .pill.routine { color: #0a7a52; border-color: #0a7a52; }' ...
'.plan-box { border: 1px solid; border-radius: 8px; padding: 12px 16px; margin-top: 12px; }' ...
'.plan-box.priority { background: #fdf1f3; border-color: #f3c6ce; } .plan-box.review { background: #fdf7ea; border-color: #f3dfaa; } .plan-box.routine { background: #eefaf4; border-color: #b9e4cf; }' ...
'.plan-label { font-size: 9.5px; text-transform: uppercase; font-weight: 700; color: #8792a1; letter-spacing: 0.03em; }' ...
'.plan-text { font-size: 13px; font-weight: 700; margin-top: 5px; color: #1b2430; }' ...
'.disagree-banner { border: 1px solid #f3c6ce; background: #fdf1f3; border-radius: 8px; padding: 12px 16px; margin-top: 12px; }' ...
'.disagree-title { font-size: 12px; font-weight: 700; color: #c11d3f; }' ...
'.disagree-body { font-size: 11px; color: #8f1c33; margin-top: 4px; }' ...
'.findings-row { display: flex; gap: 26px; align-items: flex-start; }' ...
'.fundus-box { border: 1px solid #d0d5db; border-radius: 8px; overflow: hidden; width: 230px; flex-shrink: 0; }' ...
'.fundus-box img { width: 100%; display: block; background: #0a0a0a; }' ...
'.quality-pill-row { margin-top: 10px; }' ...
'table.findings { width: 100%; border-collapse: collapse; font-size: 11px; }' ...
'table.findings th { text-align: left; font-size: 9.5px; text-transform: uppercase; color: #8792a1; padding: 0 8px 6px; border-bottom: 1.5px solid #1b2430; }' ...
'table.findings td { padding: 7px 8px; border-bottom: 1px solid #eef1f5; }' ...
'table.findings td.lt { font-weight: 700; } table.findings td.loc { color: #64748b; }' ...
'table.findings tr:nth-child(even) { background: #fafbfc; }' ...
'.conf { font-weight: 700; padding: 2px 9px; border-radius: 999px; font-size: 10.5px; }' ...
'.conf.reliable { color: #0a7a52; background: #eafaf3; } .conf.moderate { color: #b56a08; background: #fdf6e5; } .conf.low { color: #c11d3f; background: #fdeef1; }' ...
'.infogrid { display: grid; grid-template-columns: repeat(4, 1fr); gap: 14px; }' ...
'.infogrid .val.danger { color: #c11d3f; } .infogrid .val.success { color: #0a7a52; } .infogrid .val.warn { color: #b56a08; }' ...
'.viz-row { display: flex; gap: 22px; }' ...
'.viz-col { flex: 1; }' ...
'.viz-col img { width: 100%; border-radius: 8px; border: 1px solid #d0d5db; display: block; }' ...
'.viz-caption { text-align: center; font-size: 9.5px; color: #8792a1; margin-top: 6px; }' ...
'.legend { display: grid; grid-template-columns: repeat(2, 1fr); gap: 4px 14px; margin-top: 10px; font-size: 10px; color: #475569; }' ...
'.legend .swatch { display: inline-block; width: 10px; height: 10px; border: 0.5px solid #94a3b8; border-radius: 2px; margin-right: 6px; vertical-align: middle; }' ...
'.page-break { page-break-before: always; }' ...
'table.reasons { width: 100%; border-collapse: collapse; font-size: 10.5px; margin-top: 6px; }' ...
'table.reasons th { text-align: left; font-size: 9px; text-transform: uppercase; color: #8792a1; padding: 0 8px 6px; border-bottom: 1.5px solid #1b2430; }' ...
'table.reasons td { padding: 6px 8px; border-bottom: 1px solid #eef1f5; }' ...
'table.reasons tr:nth-child(even) { background: #fafbfc; }' ...
'.reasoning-block { margin-top: 16px; font-size: 11px; }' ...
'.reasoning-label { font-weight: 700; color: #475569; margin-top: 10px; }' ...
'.note-warn { font-size: 10px; color: #b56a08; font-style: italic; margin-top: 8px; }' ...
'.disclaimer { font-size: 9.5px; color: #8792a1; font-style: italic; margin-top: 26px; padding-top: 12px; border-top: 1px solid #eef1f5; }' ...
'.footer-row { display: flex; justify-content: space-between; align-items: flex-end; margin-top: 20px; }' ...
'.signature { text-align: center; width: 190px; }' ...
'.signature .line { border-top: 1px solid #94a3b8; margin-bottom: 4px; }' ...
    ];
end

% ============================================================
% Small helpers
% ============================================================

function cat = resultCategoryOf(gradeResult)
    if gradeResult.flag.flagged
        cat = ternary(strcmp(gradeResult.flag.priority, 'high'), 'PRIORITY', 'REVIEW');
    elseif gradeResult.shownGrade >= 3
        cat = 'PRIORITY';
    elseif gradeResult.shownGrade == 2
        cat = 'REVIEW';
    else
        cat = 'ROUTINE';
    end
end

function [pillClass, planClass] = toneClasses(resultCategory)
    switch resultCategory
        case 'PRIORITY'
            pillClass = 'priority'; planClass = 'priority';
        case 'REVIEW'
            pillClass = 'review'; planClass = 'review';
        otherwise
            pillClass = 'routine'; planClass = 'routine';
    end
end

function cls = reliabilityClass(category)
    switch category
        case 'Reliable'
            cls = 'reliable';
        case 'Moderate'
            cls = 'moderate';
        otherwise
            cls = 'low';
    end
end

function label = qualityCategoryLabel(decision)
    switch char(decision)
        case 'Pass'
            label = 'PASS';
        case 'Enhance'
            label = 'ACCEPTABLE';
        case 'Reject'
            label = 'REJECT';
        otherwise
            label = upper(char(decision));
    end
end

function label = gradeLabel(grade)
    labels = {'No DR', 'Mild NPDR', 'Moderate NPDR', 'Severe NPDR', 'Proliferative DR'};
    if grade >= 0 && grade <= 4
        label = labels{grade + 1};
    else
        label = 'Unknown';
    end
end

function str = valueOrUnknown(s, fieldName, fmt)
    if isfield(s, fieldName) && ~isempty(s.(fieldName))
        str = sprintf(fmt, s.(fieldName));
    else
        str = 'Unknown';
    end
end

function out = ternary(cond, a, b)
    if cond, out = a; else, out = b; end
end

function esc = htmlEscape(str)
    str = char(str);
    esc = strrep(str, '&', '&amp;');
    esc = strrep(esc, '<', '&lt;');
    esc = strrep(esc, '>', '&gt;');
end
